# Generated by Django 4.2.23 on 2026-04-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgwrecord',
            name='charging_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pgwrecord',
            name='data_volume_down',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='pgwrecord',
            name='data_volume_up',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
