# Generated by Django 4.2.23 on 2026-04-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgw', '0002_alter_pgwrecord_charging_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgwrecord',
            name='rating_group',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
