# Generated by Django 4.2.23 on 2026-04-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgw', '0003_pgwrecord_rating_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgwrecord',
            name='rating_group',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
