# Generated by Django 4.2.23 on 2026-04-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgw', '0006_pgwrecord_eci_pgwrecord_tac'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgwrecord',
            name='apn_oi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pgwrecord',
            name='charging_characteristics',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pgwrecord',
            name='diagnostics',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pgwrecord',
            name='local_sequence_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pgwrecord',
            name='ms_timezone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pgwrecord',
            name='pdn_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pgwrecord',
            name='pdn_type_raw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pgwrecord',
            name='qci',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pgwrecord',
            name='record_sequence_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pgwrecord',
            name='uli_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pgwrecord',
            name='user_location_info',
            field=models.TextField(blank=True),
        ),
    ]
