# Generated by Django 4.2.23 on 2026-04-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgw', '0007_pgwrecord_apn_oi_pgwrecord_charging_characteristics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgwrecord',
            name='ch_selection_mode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pgwrecord',
            name='dynamic_address_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pgwrecord',
            name='ims_signaling_context',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pgwrecord',
            name='max_requested_bw_dl',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pgwrecord',
            name='max_requested_bw_ul',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pgwrecord',
            name='rule_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pgwrecord',
            name='selection_mode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pgwrecord',
            name='serving_node_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
