from django.urls import path

from . import views

app_name = 'drive_test'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('sessions/', views.session_list, name='session_list'),
    path('sessions/upload/', views.session_upload, name='session_upload'),
    path('sessions/upload/preview/', views.session_upload_preview, name='session_upload_preview'),
    path('sessions/upload/status/<int:file_id>/', views.session_upload_status, name='session_upload_status'),
    path('sessions/<str:session_ref>/', views.session_detail, name='session_detail'),
    path('sessions/<str:session_ref>/map-data/', views.session_map_data, name='session_map_data'),
    path('sessions/<str:session_ref>/measurements/', views.session_measurements, name='session_measurements'),
    path('sessions/<str:session_ref>/findings/', views.session_findings, name='session_findings'),
    path('sessions/<str:session_ref>/kpis/', views.session_kpis, name='session_kpis'),
    path('sessions/<str:session_ref>/timeseries/', views.session_timeseries, name='session_timeseries'),
    path('sessions/<str:session_ref>/workspace/', views.session_workspace, name='session_workspace'),
    path('sessions/<str:session_ref>/report/excel/', views.session_report_excel, name='session_report_excel'),
    path('map-data/', views.dashboard_map_data, name='map_data'),
    path('dashboard-trend/', views.dashboard_trend, name='dashboard_trend'),
    path('sites/', views.site_list, name='site_list'),
    path('sites/map/', views.site_map_data, name='site_map_data'),
    path('sites/add/', views.site_create, name='site_create'),
    path('sites/<int:pk>/', views.site_detail, name='site_detail'),
    path('sites/<int:pk>/edit/', views.site_edit, name='site_edit'),
    path('sectors/', views.sector_list, name='sector_list'),
    path('sectors/map/', views.sector_map_data, name='sector_map_data'),
    path('sectors/add/', views.sector_create, name='sector_create'),
    path('sectors/<int:pk>/', views.sector_detail, name='sector_detail'),
    path('sectors/<int:pk>/edit/', views.sector_edit, name='sector_edit'),
    path('cells/', views.cell_list, name='cell_list'),
    path('cells/map/', views.cell_map_data, name='cell_map_data'),
    path('cells/add/', views.cell_create, name='cell_create'),
    path('cells/<int:pk>/', views.cell_detail, name='cell_detail'),
    path('cells/<int:pk>/edit/', views.cell_edit, name='cell_edit'),
    path('measurements/', views.measurement_list, name='measurement_list'),
    path('measurements/<int:pk>/', views.measurement_detail, name='measurement_detail'),
    path('cell-matching/', views.cell_matching, name='cell_matching'),
    path('data-quality/', views.data_quality, name='data_quality'),
    path('data-quality/api/<str:session_ref>/', views.data_quality_session_detail, name='data_quality_session_detail'),
    path('kpis/', views.kpi_analysis, name='kpi_analysis'),
    path('operator-analysis/', views.operator_analysis, name='operator_analysis'),
    path('processing/', views.processing_monitor, name='processing_monitor'),
    path('processing/<int:file_id>/', views.processing_detail, name='processing_detail'),
    path('rules/', views.rules_thresholds, name='rules_thresholds'),
    path('rules/add/', views.rule_create, name='rule_create'),
    path('rules/<int:pk>/', views.rule_detail, name='rule_detail'),
    path('rules/<int:pk>/edit/', views.rule_edit, name='rule_edit'),
    path('rules/<int:pk>/toggle/', views.rule_toggle_active, name='rule_toggle_active'),
    path('thresholds/add/', views.threshold_create, name='threshold_create'),
    path('thresholds/<int:pk>/', views.threshold_detail, name='threshold_detail'),
    path('thresholds/<int:pk>/edit/', views.threshold_edit, name='threshold_edit'),
    path('thresholds/<int:pk>/expire/', views.threshold_expire, name='threshold_expire'),
    path('audit/', views.audit_trail, name='audit_trail'),
    path('audit/<str:entry_id>/', views.audit_detail, name='audit_detail'),
    path('reports/', views.report_list, name='report_list'),
    path('reports/generate/', views.report_generate, name='report_generate'),
    path('reports/<str:report_ref>/', views.report_detail, name='report_detail'),
    path('reports/<str:report_ref>/download/', views.report_download, name='report_download'),
    path('reports/<str:report_ref>/pdf/', views.report_pdf, name='report_pdf'),
    path('reports/<str:report_ref>/map-data/', views.report_map_data, name='report_map_data'),
    path('gis/', views.gis, name='gis'),
    path('gis/data/', views.gis_data, name='gis_data'),
    path('findings/', views.finding_list, name='finding_list'),
    path('findings/map/', views.finding_map_data, name='finding_map_data'),
    path('findings/export/', views.finding_export, name='finding_export'),
    path('findings/<int:pk>/', views.finding_detail, name='finding_detail'),
    path('findings/<int:pk>/status/', views.finding_set_status, name='finding_set_status'),
    path('reference/import/', views.reference_import, name='reference_import'),

    # Benchmark Comparison Engine
    path('benchmark/', views.benchmark_dashboard, name='benchmark_dashboard'),
    path('benchmark/campaigns/', views.benchmark_campaign_list, name='benchmark_campaign_list'),
    path('benchmark/campaigns/new/', views.benchmark_campaign_create, name='benchmark_campaign_create'),
    path('benchmark/campaigns/<str:ref>/', views.benchmark_campaign_detail, name='benchmark_campaign_detail'),
    path('benchmark/campaigns/<str:ref>/score/', views.benchmark_campaign_score, name='benchmark_campaign_score'),
]
