# Generated by Django 4.2.23 on 2026-05-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_lawful_intercept',
            field=models.BooleanField(default=False, help_text='Can open / execute / export lawful-intercept (LEA) requests'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('UPLOAD', 'File Upload'), ('PROCESS', 'Process'), ('EXPORT', 'Export'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGULATORY_REPORT_GENERATED', 'Regulatory Report Generated'), ('LEVY_COMPUTED', 'Levy Computed'), ('LEVY_PAID', 'Levy Paid'), ('LEA_REQUEST_OPENED', 'LEA Request Opened'), ('LEA_QUERY_EXECUTED', 'LEA Query Executed'), ('LEA_EXPORT', 'LEA Evidentiary Export')], max_length=32),
        ),
    ]
