# Generated by Django 4.2.23 on 2026-05-22 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_can_lawful_intercept_alter_auditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(db_index=True, help_text='e.g. interconnect.generate_invoice, regulatory.generate_report', max_length=80)),
                ('label', models.CharField(help_text='Human-readable description shown in the UI', max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('REVOKED', 'Cancelled')], db_index=True, default='PENDING', max_length=10)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('params', models.JSONField(blank=True, default=dict, help_text='Input arguments for traceability')),
                ('result', models.JSONField(blank=True, default=dict, help_text='Result payload on success')),
                ('error_message', models.TextField(blank=True)),
                ('progress_pct', models.IntegerField(default=0, help_text='0-100; engines can update this to show progress')),
                ('progress_message', models.CharField(blank=True, max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('result_entity_type', models.CharField(blank=True, max_length=50)),
                ('result_entity_id', models.CharField(blank=True, max_length=50)),
                ('result_url', models.CharField(blank=True, help_text='Page to navigate to on success (e.g. invoice detail)', max_length=300)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Record',
                'verbose_name_plural': 'Job Records',
                'db_table': 'job_records',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
