# Generated by Django 4.2.23 on 2026-09-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('hostname', models.CharField(blank=True, max_length=120)),
                ('cpu_percent', models.FloatField(default=0.0)),
                ('memory_percent', models.FloatField(default=0.0)),
                ('memory_used_bytes', models.BigIntegerField(default=0)),
                ('memory_total_bytes', models.BigIntegerField(default=0)),
                ('disk_percent', models.FloatField(default=0.0)),
                ('disk_used_bytes', models.BigIntegerField(default=0)),
                ('disk_free_bytes', models.BigIntegerField(default=0)),
                ('network_rx_bytes', models.BigIntegerField(default=0)),
                ('network_tx_bytes', models.BigIntegerField(default=0)),
                ('network_percent', models.FloatField(default=0.0)),
                ('load_average', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'System Metric Snapshot',
                'verbose_name_plural': 'System Metric Snapshots',
                'db_table': 'system_metric_snapshots',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='system_metr_timesta_1d5dd8_idx')],
            },
        ),
    ]
