# Generated by Django 4.2.23 on 2026-09-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_systemmetricsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_auditor',
            field=models.BooleanField(default=False, help_text='Can manage audit cases and view detailed reconciliation'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_regulator',
            field=models.BooleanField(default=False, help_text='Can view regulatory dashboards, traffic monitoring and reports'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_regulatory_admin',
            field=models.BooleanField(default=False, help_text='Can manage tariffs, tax rates, risk rules and regulatory configuration'),
        ),
    ]
