# Generated by Django 4.2.23 on 2026-09-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_is_auditor_user_is_regulator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('cpu_percent', 'CPU Utilisation (%)'), ('memory_percent', 'Memory Utilisation (%)'), ('disk_percent', 'Disk Utilisation (%)'), ('collection_backlog_count', 'Collection Backlog (file count)'), ('collection_backlog_age', 'Collection Backlog Oldest File (seconds)'), ('processing_backlog_count', 'Processing Backlog (file count)'), ('output_staging_count', 'Output Staging Backlog (file count)'), ('distribution_failure_count', 'Distribution Failures (count in window)'), ('decoder_failure_count', 'Decoder Failures (count in window)'), ('processing_latency', 'Avg Processing Latency (seconds)')], max_length=50, unique=True)),
                ('warning_threshold', models.FloatField(help_text='Value at which a WARNING alert is raised')),
                ('major_threshold', models.FloatField(help_text='Value at which a MAJOR/ERROR alert is raised')),
                ('critical_threshold', models.FloatField(help_text='Value at which a CRITICAL alert is raised')),
                ('enabled', models.BooleanField(default=True)),
                ('evaluation_window_seconds', models.IntegerField(default=300, help_text='Time window (seconds) over which count-based metrics are evaluated')),
                ('notes', models.TextField(blank=True, help_text='INITIAL OPERATIONAL DEFAULT — subject to Operations approval')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alert Threshold',
                'verbose_name_plural': 'Alert Thresholds',
                'db_table': 'alert_thresholds',
                'ordering': ['metric'],
            },
        ),
    ]
