# Generated by Django 4.2.23 on 2026-09-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_system_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertthreshold',
            name='metric',
            field=models.CharField(choices=[('cpu_percent', 'CPU Utilisation (%)'), ('memory_percent', 'Memory Utilisation (%)'), ('disk_percent', 'Disk Utilisation (%)'), ('collection_backlog_count', 'Collection Backlog (file count)'), ('collection_backlog_age', 'Collection Backlog Oldest File (seconds)'), ('processing_backlog_count', 'Processing Backlog (file count)'), ('output_staging_count', 'Output Staging Backlog (file count)'), ('distribution_failure_count', 'Distribution Failures (count in window)'), ('decoder_failure_count', 'Decoder Failures (count in window)'), ('processing_latency', 'Avg Processing Latency (seconds)'), ('zero_record_file_count', 'Empty Files Received (count in window)'), ('source_not_sending_hours', 'Source Silent Duration (hours)'), ('worker_count', 'Available Celery Workers')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='systemcontrol',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
