# Generated by Django 4.2.23 on 2026-04-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrichmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('stream', models.CharField(max_length=20)),
                ('target_field', models.CharField(max_length=100)),
                ('source_field', models.CharField(blank=True, max_length=100)),
                ('transform', models.CharField(choices=[('COPY', 'Copy from source'), ('DEFAULT', 'Set default value'), ('FIRST_N', 'First N digits'), ('LOOKUP', 'Reference table lookup'), ('REGEX_EXTRACT', 'Regex extract')], max_length=30)),
                ('transform_value', models.CharField(blank=True, max_length=500)),
                ('condition', models.CharField(choices=[('IF_EMPTY', 'Only if target is empty'), ('ALWAYS', 'Always apply'), ('IF_SMS', 'Only for SMS records')], default='IF_EMPTY', max_length=30)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=100)),
            ],
            options={
                'db_table': 'enrichment_rules',
                'ordering': ['stream', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('stream', models.CharField(help_text='MSC, PGW, SGSN, SGW, or ALL', max_length=20)),
                ('field_name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('REQUIRED', 'Required'), ('MAX_LENGTH', 'Max Length'), ('PATTERN', 'Regex Pattern'), ('RANGE', 'Numeric Range')], max_length=20)),
                ('rule_value', models.CharField(max_length=500)),
                ('error_message', models.CharField(blank=True, max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=100)),
            ],
            options={
                'db_table': 'validation_rules',
                'ordering': ['stream', 'priority'],
            },
        ),
    ]
