# Generated by Django 4.2.23 on 2026-04-15 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('SFTP', 'SFTP Remote'), ('LOCAL', 'Local Directory'), ('API', 'API Push'), ('MANUAL', 'Manual Upload')], default='MANUAL', max_length=10)),
                ('decoder_type', models.CharField(choices=[('MSC', 'MSC (Huawei ASN.1/BER)'), ('PGW', 'PGW (3GPP PS Domain)'), ('SGSN', 'SGSN (3GPP PS Domain)'), ('SGW', 'SGW (3GPP PS Domain)'), ('OCS', 'OCS Input'), ('CBS', 'CBS Output'), ('AUTO', 'Auto-detect'), ('CSV', 'Pre-decoded CSV')], default='AUTO', max_length=10)),
                ('vendor', models.CharField(blank=True, help_text='Equipment vendor (e.g. Huawei)', max_length=50)),
                ('network_element', models.CharField(blank=True, help_text='e.g. MSC01, PGW01', max_length=50)),
                ('sftp_host', models.CharField(blank=True, max_length=200)),
                ('sftp_port', models.IntegerField(blank=True, default=22)),
                ('sftp_username', models.CharField(blank=True, max_length=100)),
                ('sftp_password', models.CharField(blank=True, max_length=200)),
                ('sftp_key_path', models.CharField(blank=True, max_length=500)),
                ('sftp_remote_path', models.CharField(blank=True, max_length=500)),
                ('sftp_file_pattern', models.CharField(blank=True, default='*.dat', help_text='Glob pattern to match CDR files', max_length=200)),
                ('local_path', models.CharField(blank=True, max_length=500)),
                ('poll_interval_seconds', models.IntegerField(default=300, help_text='Seconds between collection polls')),
                ('enabled', models.BooleanField(default=True)),
                ('last_poll_time', models.DateTimeField(blank=True, null=True)),
                ('last_poll_status', models.CharField(blank=True, max_length=50)),
                ('files_collected', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Source',
                'verbose_name_plural': 'Data Sources',
                'db_table': 'data_sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CDRFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('file_path', models.CharField(max_length=1000)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('decoder_type', models.CharField(choices=[('MSC', 'MSC (Huawei ASN.1/BER)'), ('PGW', 'PGW (3GPP PS Domain)'), ('SGSN', 'SGSN (3GPP PS Domain)'), ('SGW', 'SGW (3GPP PS Domain)'), ('OCS', 'OCS Input'), ('CBS', 'CBS Output'), ('AUTO', 'Auto-detect'), ('CSV', 'Pre-decoded CSV')], default='AUTO', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('DUPLICATE', 'Duplicate')], db_index=True, default='PENDING', max_length=15)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('records_total', models.IntegerField(default=0)),
                ('records_valid', models.IntegerField(default=0)),
                ('records_invalid', models.IntegerField(default=0)),
                ('records_duplicate', models.IntegerField(default=0)),
                ('processing_started', models.DateTimeField(blank=True, null=True)),
                ('processing_completed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdr_files', to='collection.datasource')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CDR File',
                'verbose_name_plural': 'CDR Files',
                'db_table': 'cdr_files',
                'ordering': ['-created_at'],
            },
        ),
    ]
