# Generated by Django 4.2.23 on 2026-04-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short identifier shown in the tree, e.g. SL_BIGDATA_HMSC', max_length=100, unique=True)),
                ('label', models.CharField(help_text='Display label, e.g. HMSC', max_length=100)),
                ('group', models.CharField(help_text='Group key used to cluster portals, e.g. SL_BIGDATA', max_length=100)),
                ('group_label', models.CharField(blank=True, help_text='Human-readable group name shown in the tree. Falls back to group if blank.', max_length=100)),
                ('decoder_type', models.CharField(choices=[('MSC', 'MSC (Huawei ASN.1/BER)'), ('PGW', 'PGW (3GPP PS Domain)'), ('SGSN', 'SGSN (3GPP PS Domain)'), ('SGW', 'SGW (3GPP PS Domain)'), ('OCS', 'OCS Input'), ('CBS', 'CBS Output'), ('AUTO', 'Auto-detect'), ('CSV', 'Pre-decoded CSV')], help_text='Which CDR stream this portal receives (MSC, PGW, SGW, SGSN …)', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Distribution Portal',
                'verbose_name_plural': 'Distribution Portals',
                'db_table': 'distribution_portals',
                'ordering': ['group', 'label'],
            },
        ),
    ]
