# Generated by Django 4.2.23 on 2026-04-25 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0007_add_vendor'),
        ('collection', '0003_seed_distribution_portals'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionportal',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor / destination system this portal belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_portals', to='reference.vendor'),
        ),
        migrations.AlterField(
            model_name='distributionportal',
            name='group',
            field=models.CharField(blank=True, help_text='Fallback group key when vendor is not set', max_length=100),
        ),
        migrations.AlterField(
            model_name='distributionportal',
            name='group_label',
            field=models.CharField(blank=True, help_text='Fallback group label when vendor is not set', max_length=100),
        ),
    ]
