# Generated by Django 4.2.23 on 2026-04-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_distribution_portal_output_fk_and_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
