# Generated by Django 4.2.23 on 2026-04-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_alter_distributionlog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionlog',
            name='retry_count',
            field=models.IntegerField(default=0, help_text='Number of retry attempts performed'),
        ),
    ]
