# Generated by Django 4.2.23 on 2026-04-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_distributionlog_retry_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='cbs_type_hint',
            field=models.CharField(blank=True, help_text='CBS sub-type override when filename detection is insufficient (RECHARGE, VOICE, SMS, DATA, MON, CM, LOAN, ADJUSTMENT)', max_length=20),
        ),
    ]
