# Generated by Django 4.2.23 on 2026-05-16 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_datasource_cbs_type_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdrfile',
            name='decoder_type',
            field=models.CharField(choices=[('MSC', 'MSC (Huawei ASN.1/BER)'), ('IMS', 'IMS (Huawei ATS9900 VoLTE/VoBB)'), ('PGW', 'PGW (3GPP PS Domain)'), ('SGSN', 'SGSN (3GPP PS Domain)'), ('SGW', 'SGW (3GPP PS Domain)'), ('OCS', 'OCS Input'), ('CBS', 'CBS Output'), ('AUTO', 'Auto-detect'), ('CSV', 'Pre-decoded CSV')], default='AUTO', max_length=10),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='decoder_type',
            field=models.CharField(choices=[('MSC', 'MSC (Huawei ASN.1/BER)'), ('IMS', 'IMS (Huawei ATS9900 VoLTE/VoBB)'), ('PGW', 'PGW (3GPP PS Domain)'), ('SGSN', 'SGSN (3GPP PS Domain)'), ('SGW', 'SGW (3GPP PS Domain)'), ('OCS', 'OCS Input'), ('CBS', 'CBS Output'), ('AUTO', 'Auto-detect'), ('CSV', 'Pre-decoded CSV')], default='AUTO', max_length=10),
        ),
        migrations.AlterField(
            model_name='distributionportal',
            name='decoder_type',
            field=models.CharField(choices=[('MSC', 'MSC (Huawei ASN.1/BER)'), ('IMS', 'IMS (Huawei ATS9900 VoLTE/VoBB)'), ('PGW', 'PGW (3GPP PS Domain)'), ('SGSN', 'SGSN (3GPP PS Domain)'), ('SGW', 'SGW (3GPP PS Domain)'), ('OCS', 'OCS Input'), ('CBS', 'CBS Output'), ('AUTO', 'Auto-detect'), ('CSV', 'Pre-decoded CSV')], help_text='Which CDR stream this portal receives (MSC, PGW, SGW, SGSN …)', max_length=10),
        ),
        migrations.CreateModel(
            name='ProcessingError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_seq', models.IntegerField(blank=True, help_text='Sequence number of the record within the file (1-based).', null=True)),
                ('stage', models.CharField(choices=[('DECODE', 'Decode'), ('CREATE', 'Create record'), ('VALIDATE', 'Validate'), ('ENRICH', 'Enrich'), ('PERSIST', 'Persist'), ('DISPATCH', 'Dispatch')], db_index=True, default='CREATE', max_length=12)),
                ('error_class', models.CharField(blank=True, max_length=120)),
                ('error_message', models.TextField()),
                ('raw_hex', models.CharField(blank=True, help_text='First ~100 bytes of the failing record in hex.', max_length=400)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Free-form context (tag offsets, decoder state).')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cdr_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_errors', to='collection.cdrfile')),
            ],
            options={
                'verbose_name': 'Processing Error',
                'verbose_name_plural': 'Processing Errors',
                'db_table': 'processing_errors',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cdr_file', 'created_at'], name='processing__cdr_fil_89ca1e_idx')],
            },
        ),
    ]
