# Generated by Django 4.2.23 on 2026-06-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_alter_cdrfile_decoder_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdrfile',
            name='network_element',
            field=models.CharField(blank=True, help_text='e.g. msc, pgw, ims', max_length=10),
        ),
        migrations.AddField(
            model_name='cdrfile',
            name='operator_code',
            field=models.SlugField(blank=True, help_text='Operator slug, e.g. orange', max_length=30),
        ),
        migrations.AddField(
            model_name='cdrfile',
            name='vendor',
            field=models.SlugField(blank=True, help_text='Equipment vendor, e.g. huawei', max_length=30),
        ),
    ]
