# Generated by Django 4.2.23 on 2026-06-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_cdrfile_network_element_cdrfile_operator_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdrfile',
            name='records_by_type',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
