# Generated by Django 4.2.23 on 2026-09-08 17:43

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0012_cdrfile_records_by_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdrfile',
            name='status',
            field=models.CharField(choices=[('COLLECTED', 'Collected'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DECODED', 'Decoded'), ('DISPATCHING', 'Dispatching'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('DUPLICATE', 'Duplicate')], db_index=True, default='COLLECTED', max_length=15),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='sftp_password',
            field=core.fields.EncryptedCharField(blank=True, max_length=500),
        ),
    ]
