# Generated by Django 4.2.23 on 2026-09-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0014_encrypt_existing_passwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdrfile',
            name='decoder_type',
            field=models.CharField(choices=[('MSC', 'MSC (Huawei ASN.1/BER)'), ('IMS', 'IMS (Huawei ATS9900 VoLTE/VoBB)'), ('PGW', 'PGW (3GPP PS Domain)'), ('SGSN', 'SGSN (3GPP PS Domain)'), ('SGW', 'SGW (3GPP PS Domain)'), ('OCS', 'OCS Input'), ('CBS', 'CBS Output'), ('AUTO', 'Auto-detect'), ('CSV', 'Pre-decoded CSV'), ('FORWARD', 'Pass-through (forward without decoding)')], default='AUTO', max_length=10),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='decoder_type',
            field=models.CharField(choices=[('MSC', 'MSC (Huawei ASN.1/BER)'), ('IMS', 'IMS (Huawei ATS9900 VoLTE/VoBB)'), ('PGW', 'PGW (3GPP PS Domain)'), ('SGSN', 'SGSN (3GPP PS Domain)'), ('SGW', 'SGW (3GPP PS Domain)'), ('OCS', 'OCS Input'), ('CBS', 'CBS Output'), ('AUTO', 'Auto-detect'), ('CSV', 'Pre-decoded CSV'), ('FORWARD', 'Pass-through (forward without decoding)')], default='AUTO', max_length=10),
        ),
        migrations.AlterField(
            model_name='distributionportal',
            name='decoder_type',
            field=models.CharField(choices=[('MSC', 'MSC (Huawei ASN.1/BER)'), ('IMS', 'IMS (Huawei ATS9900 VoLTE/VoBB)'), ('PGW', 'PGW (3GPP PS Domain)'), ('SGSN', 'SGSN (3GPP PS Domain)'), ('SGW', 'SGW (3GPP PS Domain)'), ('OCS', 'OCS Input'), ('CBS', 'CBS Output'), ('AUTO', 'Auto-detect'), ('CSV', 'Pre-decoded CSV'), ('FORWARD', 'Pass-through (forward without decoding)')], help_text='Which CDR stream this portal receives (MSC, PGW, SGW, SGSN …)', max_length=10),
        ),
    ]
