# Generated by Django 4.2 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0015_alter_cdrfile_decoder_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdrfile',
            name='status',
            field=models.CharField(
                choices=[
                    ('COLLECTED', 'Collected'),
                    ('PENDING', 'Pending'),
                    ('PROCESSING', 'Processing'),
                    ('DECODED', 'Decoded'),
                    ('DISPATCHING', 'Dispatching'),
                    ('COMPLETED', 'Completed'),
                    ('FAILED', 'Failed'),
                    ('DUPLICATE', 'Duplicate'),
                    ('STAGED', 'Staged (in staging directory)'),
                    ('PUBLISHED', 'Published (in stream root)'),
                ],
                db_index=True,
                default='COLLECTED',
                max_length=15
            ),
        ),
        migrations.AddField(
            model_name='cdrfile',
            name='cbs_substream',
            field=models.CharField(blank=True, help_text='CBS substream (data, voice, sms, recharge) for CBS files', max_length=50),
        ),
        migrations.AddField(
            model_name='cdrfile',
            name='staging_path',
            field=models.CharField(blank=True, db_index=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='cdrfile',
            name='published_path',
            field=models.CharField(blank=True, db_index=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='cdrfile',
            name='archive_path',
            field=models.CharField(blank=True, db_index=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='cdrfile',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='cdrfile',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
