# Generated by Django 4.2.23 on 2026-09-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0018_cdrfile_empty_status_and_min_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdrfile',
            name='status',
            field=models.CharField(choices=[('COLLECTED', 'Collected'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DECODED', 'Decoded'), ('DISPATCHING', 'Dispatching'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EMPTY', 'Empty (0 records)'), ('DUPLICATE', 'Duplicate'), ('STAGED', 'Staged (in staging directory)'), ('PUBLISHED', 'Published (in stream root)')], db_index=True, default='COLLECTED', max_length=15),
        ),
    ]
