# Generated by Django 5.2.17 on 2026-09-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0019_alter_cdrfile_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="distributionlog",
            name="skip_reason",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
