# Generated by Django 4.2.23 on 2026-04-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='category',
            field=models.CharField(choices=[('AM_OUT_OF_BAND', 'AM Out-of-Band'), ('BATCH_REPAIR', 'Batch Repair'), ('CORRELATION', 'Correlation'), ('DATA_VISIBILITY', 'Data Visibility'), ('DISPLAY', 'Display'), ('DUPLICATE_CHECK', 'Duplicate Check'), ('ERROR_CORRECTION', 'Error Correction'), ('FIELD_SECURITY', 'Field Security'), ('FILE_NAMING', 'File Naming'), ('KEY_EXTRACT', 'Key Extract'), ('LARGE_FILE_INPUT', 'Large File Input'), ('OUTPUT_PROCESSING', 'Output Processing'), ('RECORD_SEARCH', 'Record Search'), ('RECORD_VALIDATION', 'Record Validation'), ('STATISTICS', 'Statistics'), ('SUBROUTINE', 'Subroutine'), ('TEST_DATA', 'Test Data'), ('TRANSFORM', 'Transform')], default='DISPLAY', max_length=50),
        ),
    ]
