# Generated by Django 4.2 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_script_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_id', models.CharField(help_text='Unique identifier for the script (e.g., sftp_orange_pgw)', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable script name', max_length=200)),
                ('purpose', models.TextField(blank=True, help_text='Description of what the script does')),
                ('script_type', models.CharField(choices=[('PYTHON', 'Python'), ('SHELL', 'Shell / Bash'), ('SQL', 'SQL')], help_text='Type of script (Python, Shell, SQL)', max_length=10)),
                ('server_path', models.CharField(help_text='Absolute path to the script on the server (e.g., /opt/ump/scripts/sftp_orange_pgw.py)', max_length=500)),
                ('version', models.CharField(help_text='Script version (e.g., 1.0.0)', max_length=50)),
                ('checksum', models.CharField(help_text='SHA-256 checksum of the script file for integrity verification', max_length=64)),
                ('enabled', models.BooleanField(default=True, help_text='Whether this script is enabled for use')),
                ('allowed_roles', models.JSONField(default=list, help_text='List of roles allowed to use this script (e.g., ["admin", "operator"])')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scripts_script_registry',
                'ordering': ['name'],
                'verbose_name': 'Script Registry',
                'verbose_name_plural': 'Script Registry',
            },
        ),
    ]
