# Generated by Django 4.2.23 on 2026-04-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputportal',
            name='base_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inputportal',
            name='connect_timeout',
            field=models.IntegerField(default=0, help_text='Connect Timeout (seconds)'),
        ),
        migrations.AddField(
            model_name='inputportal',
            name='dispatch_method',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Immediate', 'Immediate')], default='Scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='inputportal',
            name='dispatch_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inputportal',
            name='disposition',
            field=models.CharField(choices=[('MOVE', 'MOVE'), ('DELETE', 'DELETE'), ('KEEP', 'KEEP')], default='MOVE', max_length=10),
        ),
        migrations.AddField(
            model_name='inputportal',
            name='do_not_dispatch_on',
            field=models.CharField(blank=True, help_text='Comma-separated days to exclude', max_length=100),
        ),
        migrations.AddField(
            model_name='inputportal',
            name='enable_transcript',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inputportal',
            name='end_throttling_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inputportal',
            name='interval_mins',
            field=models.IntegerField(default=3, help_text='Interval in minutes'),
        ),
        migrations.AddField(
            model_name='inputportal',
            name='move_to',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='inputportal',
            name='no_dispatch_intervals',
            field=models.JSONField(blank=True, default=dict, help_text='List of start/end time ranges'),
        ),
        migrations.AddField(
            model_name='inputportal',
            name='pending_processing_throttling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inputportal',
            name='reg_pattern',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inputportal',
            name='rename_ext',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inputportal',
            name='rmv_prefix',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inputportal',
            name='schedule_type',
            field=models.CharField(choices=[('Interval', 'Interval'), ('Daily', 'Daily')], default='Interval', max_length=20),
        ),
        migrations.AddField(
            model_name='inputportal',
            name='script_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inputportal',
            name='start_throttling_counts',
            field=models.IntegerField(default=0),
        ),
    ]
