# Generated by Django 4.2.23 on 2026-04-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0002_inputportal_base_time_inputportal_connect_timeout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputportal',
            name='duplicate_business_logic',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='inputportal',
            name='duplicate_detection_algo',
            field=models.CharField(default='Disabled', max_length=50),
        ),
        migrations.AddField(
            model_name='inputportal',
            name='duplicate_directory',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='inputportal',
            name='duplicate_disposition',
            field=models.CharField(default='Transfer and Process Normally', max_length=100),
        ),
        migrations.AddField(
            model_name='inputportal',
            name='file_compression_type',
            field=models.CharField(default='No Compression', max_length=50),
        ),
        migrations.AddField(
            model_name='inputportal',
            name='input_script',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='inputportal',
            name='large_file_access_descriptor',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
