# Generated by Django 4.2.23 on 2026-04-24 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0003_inputportal_duplicate_business_logic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_type', models.CharField(choices=[('MSC', 'MSC'), ('PGW', 'PGW'), ('SGSN', 'SGSN'), ('SGW', 'SGW'), ('ALL', 'All Streams')], default='ALL', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('mapping_json', models.JSONField(default=dict, help_text="JSON mapping of Output Header -> Database Field (e.g. {'MSISDN': 'subscriber_id'})")),
                ('delimiter', models.CharField(default=',', max_length=5)),
                ('include_header', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Output Schema',
                'verbose_name_plural': 'Output Schemas',
                'db_table': 'portals_output_schema',
            },
        ),
        migrations.CreateModel(
            name='DistributionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_type', models.CharField(choices=[('MSC', 'MSC'), ('PGW', 'PGW'), ('SGSN', 'SGSN'), ('SGW', 'SGW'), ('ALL', 'All Streams')], default='ALL', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('filter_logic', models.TextField(blank=True, help_text="Python-like expression for filtering (e.g. record.account_type == 'postpaid')")),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('output_portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='portals.outputportal')),
                ('output_schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='portals.outputschema')),
            ],
            options={
                'verbose_name': 'Distribution Rule',
                'verbose_name_plural': 'Distribution Rules',
                'db_table': 'portals_distribution_rule',
                'ordering': ['priority', 'name'],
            },
        ),
    ]
