# Generated by Django 4.2.23 on 2026-04-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0004_outputschema_distributionrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionrule',
            name='filter_logic',
            field=models.TextField(blank=True, help_text='JSON dict of field=value applied via Django ORM .filter(**kwargs). Empty matches all. Example: {"prepaid_flag": "POSTPAID", "is_roaming": false}'),
        ),
    ]
