# Generated by Django 4.2.23 on 2026-04-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0005_alter_distributionrule_filter_logic'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionrule',
            name='max_retries',
            field=models.IntegerField(default=3, help_text='Total delivery attempts before giving up (1 = no retry).'),
        ),
        migrations.AddField(
            model_name='distributionrule',
            name='retry_backoff_seconds',
            field=models.CharField(blank=True, default='2,5', help_text='Comma-separated wait seconds between attempts, e.g. "2,5,10". Last value is reused if attempts exceed the list length.', max_length=100),
        ),
    ]
