# Generated by Django 4.2.23 on 2026-04-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0006_distributionrule_max_retries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionrule',
            name='stream_type',
            field=models.CharField(choices=[('MSC', 'MSC'), ('PGW', 'PGW'), ('SGSN', 'SGSN'), ('SGW', 'SGW'), ('CBS', 'CBS (Huawei OCS/CBS)'), ('ALL', 'All Streams')], default='ALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='inputportal',
            name='stream_type',
            field=models.CharField(choices=[('MSC', 'MSC'), ('PGW', 'PGW'), ('SGSN', 'SGSN'), ('SGW', 'SGW'), ('CBS', 'CBS (Huawei OCS/CBS)'), ('ALL', 'All Streams')], default='ALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='outputportal',
            name='stream_type',
            field=models.CharField(choices=[('MSC', 'MSC'), ('PGW', 'PGW'), ('SGSN', 'SGSN'), ('SGW', 'SGW'), ('CBS', 'CBS (Huawei OCS/CBS)'), ('ALL', 'All Streams')], default='ALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='outputschema',
            name='stream_type',
            field=models.CharField(choices=[('MSC', 'MSC'), ('PGW', 'PGW'), ('SGSN', 'SGSN'), ('SGW', 'SGW'), ('CBS', 'CBS (Huawei OCS/CBS)'), ('ALL', 'All Streams')], default='ALL', max_length=10),
        ),
    ]
