# Generated by Django 4.2.23 on 2026-05-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0007_alter_distributionrule_stream_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputschema',
            name='line_terminator',
            field=models.CharField(default='\n', help_text='Line endings: \\n for Unix, \\r\\n for Windows.', max_length=5),
        ),
        migrations.AddField(
            model_name='outputschema',
            name='quote_all',
            field=models.BooleanField(default=False, help_text='If true, quote all fields in CSV output.'),
        ),
        migrations.AlterField(
            model_name='outputportal',
            name='directory',
            field=models.CharField(blank=True, help_text='Absolute path OR path relative to project DATA_DIR. Supports placeholders: {stream}, {portal}, {YYYY}, {MM}, {DD}. If blank, defaults to "output/{stream}".', max_length=500),
        ),
        migrations.AlterField(
            model_name='outputportal',
            name='output_format',
            field=models.CharField(choices=[('CSV', 'CSV'), ('JSON', 'JSON'), ('XML', 'XML'), ('TEXT', 'Plain Text'), ('RAW', 'Raw Binary (No Decoding)')], default='CSV', max_length=10),
        ),
    ]
