# Generated by Django 4.2.23 on 2026-06-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0009_alter_distributionrule_stream_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputportal',
            name='directory',
            field=models.CharField(blank=True, help_text='Absolute path OR path relative to project DATA_DIR. Supports placeholders: {operator}, {vendor}, {ne}, {stream}, {portal}, {YYYY}, {MM}, {DD}. If blank, defaults to "{operator}/output/{vendor}/{ne}".', max_length=500),
        ),
    ]
