# Generated by Django 4.2.23 on 2026-09-08 17:43

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0010_alter_outputportal_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputportal',
            name='password',
            field=core.fields.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='outputportal',
            name='password',
            field=core.fields.EncryptedCharField(blank=True, max_length=500),
        ),
    ]
