# Generated by Django 4.2 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0011_encrypted_password_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputportal',
            name='landing_root',
            field=models.CharField(blank=True, help_text='Root directory for input landing (e.g., /ump/landing/input/{operator}/)', max_length=500),
        ),
        migrations.AddField(
            model_name='inputportal',
            name='staging_path',
            field=models.CharField(blank=True, help_text='Staging directory path relative to landing_root (e.g., {stream}/staging/)', max_length=500),
        ),
        migrations.AddField(
            model_name='inputportal',
            name='archive_path',
            field=models.CharField(blank=True, help_text='Archive directory path with date placeholders (e.g., /ump/archive/input/{operator}/{stream}/YYYY/MM/DD/HH/)', max_length=500),
        ),
        migrations.AddField(
            model_name='inputportal',
            name='enable_staging',
            field=models.BooleanField(default=True, help_text='Enable staging/publication semantics for this portal'),
        ),
        migrations.AddField(
            model_name='outputportal',
            name='landing_root',
            field=models.CharField(blank=True, help_text='Root directory for output landing (e.g., /ump/landing/output/{downstream}/{operator}/)', max_length=500),
        ),
        migrations.AddField(
            model_name='outputportal',
            name='staging_path',
            field=models.CharField(blank=True, help_text='Staging directory path relative to landing_root (e.g., {stream}/staging/)', max_length=500),
        ),
        migrations.AddField(
            model_name='outputportal',
            name='archive_path',
            field=models.CharField(blank=True, help_text='Archive directory path with date placeholders (e.g., /ump/archive/output/{downstream}/{operator}/{stream}/YYYY/MM/DD/HH/)', max_length=500),
        ),
        migrations.AddField(
            model_name='outputportal',
            name='enable_staging',
            field=models.BooleanField(default=True, help_text='Enable staging/publication semantics for this portal'),
        ),
    ]
