# Generated by Django 4.2 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0012_add_staging_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for this path security rule (e.g., input_landing_orange)', max_length=100, unique=True)),
                ('path_prefix', models.CharField(help_text='Allowed path prefix (e.g., /ump/landing/input/orange/)', max_length=500)),
                ('allowed_operations', models.JSONField(default=list, help_text='List of allowed operations: read, write, delete, move')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'portals_path_security',
                'ordering': ['name'],
                'verbose_name': 'Path Security Rule',
                'verbose_name_plural': 'Path Security Rules',
            },
        ),
    ]
