# Generated by Django 4.2.23 on 2026-04-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImsiPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(help_text='IMSI prefix (e.g. 61901)', max_length=15, unique=True)),
                ('mcc', models.CharField(help_text='Mobile Country Code', max_length=3)),
                ('mnc', models.CharField(help_text='Mobile Network Code', max_length=3)),
                ('operator', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('is_home', models.BooleanField(default=False, help_text='Home network (local SIM)')),
                ('enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IMSI Prefix',
                'verbose_name_plural': 'IMSI Prefixes',
                'db_table': 'ref_imsi_prefix',
                'ordering': ['prefix'],
            },
        ),
        migrations.CreateModel(
            name='NumberingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(help_text='Number prefix (e.g. 23276, 23277)', max_length=20, unique=True)),
                ('country', models.CharField(default='Sierra Leone', max_length=100)),
                ('country_code', models.CharField(blank=True, help_text='Country dialling code (e.g. 232)', max_length=5)),
                ('operator', models.CharField(max_length=200)),
                ('number_type', models.CharField(choices=[('MOBILE', 'Mobile'), ('FIXED', 'Fixed Line'), ('PREMIUM', 'Premium Rate'), ('TOLLFREE', 'Toll Free'), ('SHORTCODE', 'Short Code'), ('INTERNATIONAL', 'International'), ('SPECIAL', 'Special Service'), ('ROAMING', 'Roaming'), ('UNKNOWN', 'Unknown')], default='MOBILE', max_length=20)),
                ('min_length', models.IntegerField(default=8, help_text='Minimum total number length')),
                ('max_length', models.IntegerField(default=12, help_text='Maximum total number length')),
                ('enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Numbering Plan Entry',
                'verbose_name_plural': 'Numbering Plan',
                'db_table': 'ref_numbering_plan',
                'ordering': ['prefix'],
            },
        ),
        migrations.CreateModel(
            name='NumberRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=20, unique=True)),
                ('operator', models.CharField(max_length=200)),
                ('country', models.CharField(default='Sierra Leone', max_length=100)),
                ('service_type', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'ref_number_ranges',
                'ordering': ['prefix'],
            },
        ),
        migrations.CreateModel(
            name='TrunkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trunk_id', models.CharField(help_text='Trunk identifier used in CDRs', max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('trunk_type', models.CharField(choices=[('INTERCONNECT', 'Interconnect'), ('ROAMING', 'Roaming'), ('INTERNAL', 'Internal'), ('GATEWAY', 'Gateway'), ('OTHER', 'Other')], default='INTERCONNECT', max_length=20)),
                ('direction', models.CharField(choices=[('INCOMING', 'Incoming'), ('OUTGOING', 'Outgoing'), ('BOTH', 'Bidirectional')], default='BOTH', max_length=20)),
                ('partner', models.CharField(blank=True, help_text='Interconnect partner name', max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('prefix', models.CharField(blank=True, help_text='Associated number prefix', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Trunk Group',
                'verbose_name_plural': 'Trunk Groups',
                'db_table': 'ref_trunk_groups',
                'ordering': ['trunk_id'],
            },
        ),
        migrations.CreateModel(
            name='MccMnc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcc', models.CharField(max_length=3)),
                ('mnc', models.CharField(max_length=3)),
                ('country', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=200)),
                ('is_home', models.BooleanField(default=False, help_text='Home network flag')),
                ('enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'MCC/MNC',
                'verbose_name_plural': 'MCC/MNC Entries',
                'db_table': 'ref_mcc_mnc',
                'ordering': ['mcc', 'mnc'],
                'unique_together': {('mcc', 'mnc')},
            },
        ),
    ]
