# Generated by Django 4.2.23 on 2026-04-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mccmnc',
            name='dial_code',
            field=models.CharField(blank=True, help_text='Country dialling code (e.g. +232)', max_length=10),
        ),
        migrations.AddField(
            model_name='mccmnc',
            name='iso',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code', max_length=5),
        ),
    ]
