# Generated by Django 4.2.23 on 2026-04-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_add_iso_dialcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trunkgroup',
            options={'ordering': ['switch_id', 'trunk_id'], 'verbose_name': 'Trunk Group', 'verbose_name_plural': 'Trunk Groups'},
        ),
        migrations.AddField(
            model_name='trunkgroup',
            name='switch_id',
            field=models.CharField(blank=True, help_text='MSC/Switch identifier (e.g. FTHMSC1)', max_length=50),
        ),
        migrations.AlterField(
            model_name='trunkgroup',
            name='trunk_id',
            field=models.CharField(help_text='Trunk identifier used in CDRs', max_length=50),
        ),
        migrations.AlterField(
            model_name='trunkgroup',
            name='trunk_type',
            field=models.CharField(choices=[('INTERCONNECT', 'Interconnect'), ('ROAMING', 'Roaming / International'), ('INTERNAL', 'Internal / Onnet'), ('GATEWAY', 'Gateway'), ('OTHER', 'Other')], default='INTERCONNECT', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='trunkgroup',
            unique_together={('switch_id', 'trunk_id')},
        ),
    ]
