# Generated by Django 4.2.23 on 2026-04-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_add_switch_id_to_trunks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmscCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smsc_id', models.CharField(help_text='Short identifier used in CDRs (e.g. SMSC01)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Friendly name', max_length=200)),
                ('address', models.CharField(blank=True, help_text='GT / E.164 address or IP (e.g. +23276000001)', max_length=50)),
                ('smsc_type', models.CharField(choices=[('LOCAL', 'Local / Home'), ('INTERNATIONAL', 'International'), ('ROAMING', 'Roaming Partner'), ('PREMIUM', 'Premium Rate'), ('OTHER', 'Other')], default='LOCAL', max_length=20)),
                ('operator', models.CharField(blank=True, help_text='Owning operator', max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMSC Center',
                'verbose_name_plural': 'SMSC Centers',
                'db_table': 'ref_smsc_centers',
                'ordering': ['smsc_id'],
            },
        ),
    ]
