# Generated by Django 4.2.23 on 2026-04-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_add_smsc_centers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsccenter',
            options={'ordering': ['priority', 'smsc_id'], 'verbose_name': 'SMSC Center', 'verbose_name_plural': 'SMSC Centers'},
        ),
        migrations.AddField(
            model_name='smsccenter',
            name='priority',
            field=models.IntegerField(default=5, help_text='Routing priority (1 = highest)'),
        ),
        migrations.AddField(
            model_name='smsccenter',
            name='protocol',
            field=models.CharField(choices=[('SS7', 'SS7 / MAP'), ('SMPP', 'SMPP'), ('HTTP', 'HTTP / REST'), ('DIAMETER', 'Diameter'), ('OTHER', 'Other')], default='SMPP', max_length=20),
        ),
        migrations.AlterField(
            model_name='smsccenter',
            name='address',
            field=models.CharField(blank=True, help_text='E.164 / GT address (e.g. +23230000000)', max_length=50),
        ),
        migrations.AlterField(
            model_name='smsccenter',
            name='name',
            field=models.CharField(help_text='Friendly display name', max_length=200),
        ),
        migrations.AlterField(
            model_name='smsccenter',
            name='operator',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='smsccenter',
            name='smsc_id',
            field=models.CharField(help_text='Short identifier used in CDRs (e.g. OrangeMoney)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='smsccenter',
            name='smsc_type',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], default='EXTERNAL', max_length=20),
        ),
    ]
