# Generated by Django 4.2.23 on 2026-04-19 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0005_add_protocol_priority_to_smsc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmscCenter',
        ),
    ]
