# Generated by Django 4.2.23 on 2026-04-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0006_remove_smsc_centers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name shown in the tree, e.g. SL BIGDATA', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short uppercase code, e.g. SL_BIGDATA', max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'db_table': 'ref_vendors',
                'ordering': ['name'],
            },
        ),
    ]
