# Generated by Django 4.2.23 on 2026-05-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0007_add_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberingplan',
            name='subscriber_segment',
            field=models.CharField(blank=True, choices=[('PREPAID', 'Prepaid'), ('POSTPAID', 'Postpaid'), ('', 'Unknown / Mixed')], default='', help_text='Prepaid / Postpaid hint for this prefix range (used when CDR lacks an explicit flag).', max_length=10),
        ),
    ]
