# Generated by Django 4.2.23 on 2026-06-22 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0008_numberingplan_subscriber_segment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Lowercase slug, e.g. 'orange'. Used in paths and DB aliases.", max_length=30, unique=True)),
                ('name', models.CharField(help_text='e.g. Orange Sierra Leone', max_length=100)),
                ('home_plmn', models.CharField(help_text="e.g. '61901' (MCC+MNC)", max_length=6)),
                ('home_mcc', models.CharField(help_text="e.g. '619'", max_length=3)),
                ('home_mnc', models.CharField(help_text="e.g. '01'", max_length=3)),
                ('country_code', models.CharField(default='232', help_text="ITU dialling code, e.g. '232'", max_length=5)),
                ('postpaid_imsi_prefixes', models.JSONField(blank=True, default=list, help_text="IMSI prefixes treated as postpaid, e.g. ['6190176100']")),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Operator',
                'verbose_name_plural': 'Operators',
                'db_table': 'ref_operators',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SourcePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(help_text='Substring (default) or regex matched case-insensitively against the filename.', max_length=200)),
                ('is_regex', models.BooleanField(default=False)),
                ('vendor', models.SlugField(help_text="e.g. 'huawei', 'ericsson'", max_length=30)),
                ('network_element', models.CharField(choices=[('msc', 'MSC'), ('ims', 'IMS'), ('pgw', 'PGW'), ('sgsn', 'SGSN'), ('sgw', 'SGW'), ('cbs', 'CBS'), ('ocs', 'OCS')], help_text='Directory token / stream, e.g. msc', max_length=10)),
                ('decoder_type', models.CharField(choices=[('MSC', 'MSC (Huawei ASN.1/BER)'), ('IMS', 'IMS (Huawei ATS9900 VoLTE/VoBB)'), ('PGW', 'PGW (3GPP PS Domain)'), ('SGSN', 'SGSN (3GPP PS Domain)'), ('SGW', 'SGW (3GPP PS Domain)'), ('OCS', 'OCS Input'), ('CBS', 'CBS Output'), ('AUTO', 'Auto-detect'), ('CSV', 'Pre-decoded CSV')], default='AUTO', help_text='Leave AUTO to derive from filename/extension.', max_length=10)),
                ('priority', models.IntegerField(default=100, help_text='Lower is tried first.')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_patterns', to='reference.operator')),
            ],
            options={
                'verbose_name': 'Source Pattern',
                'verbose_name_plural': 'Source Patterns',
                'db_table': 'ref_source_patterns',
                'ordering': ['priority', 'id'],
            },
        ),
    ]
