# Generated by Django 4.2.23 on 2026-06-22 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0009_operator_sourcepattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='postpaid_imsi_prefixes',
        ),
    ]
