# Generated by Django 4.2.23 on 2026-09-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0010_remove_operator_postpaid_imsi_prefixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcepattern',
            name='decoder_type',
            field=models.CharField(choices=[('MSC', 'MSC (Huawei ASN.1/BER)'), ('IMS', 'IMS (Huawei ATS9900 VoLTE/VoBB)'), ('PGW', 'PGW (3GPP PS Domain)'), ('SGSN', 'SGSN (3GPP PS Domain)'), ('SGW', 'SGW (3GPP PS Domain)'), ('OCS', 'OCS Input'), ('CBS', 'CBS Output'), ('AUTO', 'Auto-detect'), ('CSV', 'Pre-decoded CSV'), ('FORWARD', 'Pass-through (forward without decoding)')], default='AUTO', help_text='Leave AUTO to derive from filename/extension.', max_length=10),
        ),
    ]
