# Generated by Django 4.2.23 on 2026-04-28 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0009_datasource_cbs_type_hint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbs_type', models.CharField(choices=[('RECHARGE', 'Recharge'), ('VOICE', 'Voice'), ('SMS', 'SMS'), ('DATA', 'Data'), ('MON', 'MON'), ('CM', 'CM'), ('LOAN', 'Loan'), ('ADJUSTMENT', 'Adjustment'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', help_text='CBS CDR sub-type detected from filename or DataSource hint', max_length=20)),
                ('subscriber_id', models.CharField(blank=True, db_index=True, help_text='Primary subscriber/account identifier (field[0])', max_length=100)),
                ('msisdn', models.CharField(blank=True, db_index=True, help_text='Mobile subscriber number (field[5])', max_length=20)),
                ('charge_amount', models.DecimalField(blank=True, decimal_places=6, help_text='Charge amount if present in the record', max_digits=18, null=True)),
                ('event_time', models.DateTimeField(blank=True, db_index=True, help_text='Event timestamp parsed from the CDR', null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Complete pipe-delimited record as a header-keyed dict')),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('INVALID', 'Invalid')], default='VALID', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='cbs_records', to='collection.cdrfile')),
                ('source', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.datasource')),
            ],
            options={
                'verbose_name': 'CBS CDR Record',
                'verbose_name_plural': 'CBS CDR Records',
                'db_table': 'cbs_records',
                'ordering': ['-event_time', '-id'],
                'indexes': [models.Index(fields=['cbs_type', 'event_time'], name='cbs_records_cbs_typ_c1086e_idx'), models.Index(fields=['file', 'cbs_type'], name='cbs_records_file_id_34b055_idx'), models.Index(fields=['msisdn', 'event_time'], name='cbs_records_msisdn_c502ad_idx')],
            },
        ),
    ]
