# Generated by Django 4.2.23 on 2026-05-19 08:22

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interconnect', '0006_billingcycle_is_roaming_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoamingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound roamers (we are visited PLMN)'), ('OUTBOUND', 'Outbound roamers (we are home PLMN)')], db_index=True, default='INBOUND', max_length=10)),
                ('file_number', models.CharField(help_text='TAP-style file ref, e.g. CDxxxx-IN-AFRIC-202603-1', max_length=40, unique=True)),
                ('record_count', models.IntegerField(default=0)),
                ('voice_minutes', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('sms_count', models.IntegerField(default=0)),
                ('data_mb', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('currency', models.CharField(default='SLE', max_length=3)),
                ('sdr_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), help_text='SDR conversion (Special Drawing Rights) snapshot', max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Final'), ('SENT', 'Sent to partner'), ('DISPUTED', 'Disputed'), ('SETTLED', 'Settled')], db_index=True, default='DRAFT', max_length=10)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='roaming/files/')),
                ('sha256', models.CharField(blank=True, help_text='SHA-256 of the generated file (chain of custody)', max_length=64)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('billing_cycle', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='roaming_files', to='interconnect.billingcycle')),
                ('generated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='roaming_files', to='interconnect.interconnectpartner')),
            ],
            options={
                'verbose_name': 'Roaming File',
                'verbose_name_plural': 'Roaming Files',
                'db_table': 'roaming_files',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='RoamingDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_ref', models.CharField(help_text='Partner-supplied dispute reference', max_length=60, unique=True)),
                ('raised_by', models.CharField(help_text='Partner contact name / email', max_length=120)),
                ('claimed_volume', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('claimed_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('variance_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under review'), ('ACCEPTED', 'Accepted (our side)'), ('REJECTED', 'Rejected'), ('RESOLVED', 'Resolved')], db_index=True, default='OPEN', max_length=15)),
                ('resolution_notes', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('roaming_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='roaming.roamingfile')),
            ],
            options={
                'verbose_name': 'Roaming Dispute',
                'verbose_name_plural': 'Roaming Disputes',
                'db_table': 'roaming_disputes',
                'ordering': ['-opened_at'],
            },
        ),
    ]
