# Generated by Django 4.2.23 on 2026-05-19 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interconnect', '0007_alter_exchangerate_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roamingdispute',
            name='resolved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roamingfile',
            name='billing_cycle',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='roaming_files', to='interconnect.billingcycle'),
        ),
        migrations.AlterField(
            model_name='roamingfile',
            name='generated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roamingfile',
            name='partner',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='roaming_files', to='interconnect.interconnectpartner'),
        ),
    ]
