# Generated by Django 4.2.23 on 2026-05-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interconnect', '0002_seed_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='interconnectrate',
            name='call_type',
            field=models.CharField(blank=True, help_text='Optional: Specific call type (e.g., MOC, GWOUT, SMSMO)', max_length=20, null=True),
        ),
    ]
