# Generated by Django 4.2.23 on 2026-05-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interconnect', '0003_interconnectrate_call_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='interconnectpartner',
            name='is_primary_for_country',
            field=models.BooleanField(db_index=True, default=False, help_text='When multiple partners share a country_code, this flag marks the one that receives uncategorised international traffic for that CC.'),
        ),
    ]
