# Generated by Django 4.2.23 on 2026-05-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interconnect', '0005_flag_primary_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingcycle',
            name='is_roaming',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this cycle settles via TAP-style roaming files.'),
        ),
        migrations.AddField(
            model_name='interconnectpartner',
            name='is_roaming_partner',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this operator hosts roamers we settle via TAP-style files.'),
        ),
        migrations.AddField(
            model_name='interconnectrate',
            name='is_roaming',
            field=models.BooleanField(db_index=True, default=False, help_text='True for TAP-style roaming rates (inbound/outbound roamers).'),
        ),
    ]
