# Generated by Django 4.2.23 on 2026-04-15 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSCRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(db_index=True, max_length=50)),
                ('service_type', models.CharField(db_index=True, max_length=20)),
                ('network_record_id', models.CharField(blank=True, max_length=100)),
                ('call_reference', models.CharField(blank=True, max_length=50)),
                ('call_direction', models.CharField(blank=True, max_length=5)),
                ('calling_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('called_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('dialed_number', models.CharField(blank=True, max_length=50)),
                ('charged_msisdn', models.CharField(blank=True, max_length=50)),
                ('imsi', models.CharField(blank=True, db_index=True, max_length=20)),
                ('imei', models.CharField(blank=True, max_length=20)),
                ('imsi_b', models.CharField(blank=True, max_length=20)),
                ('imei_b', models.CharField(blank=True, max_length=20)),
                ('start_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('cell_id', models.CharField(blank=True, max_length=50)),
                ('lac', models.CharField(blank=True, max_length=20)),
                ('msc_id', models.CharField(blank=True, max_length=50)),
                ('rat_type', models.CharField(blank=True, max_length=20)),
                ('originating_trunk', models.CharField(blank=True, max_length=100)),
                ('terminating_trunk', models.CharField(blank=True, max_length=100)),
                ('teleservice_code', models.CharField(blank=True, max_length=10)),
                ('bearer_service_code', models.CharField(blank=True, max_length=10)),
                ('result_code', models.CharField(blank=True, max_length=50)),
                ('roaming_indicator', models.CharField(blank=True, max_length=10)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('INVALID', 'Invalid'), ('DUPLICATE', 'Duplicate')], default='VALID', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msc_records', to='collection.cdrfile')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.datasource')),
            ],
            options={
                'verbose_name': 'MSC CDR Record',
                'verbose_name_plural': 'MSC CDR Records',
                'db_table': 'msc_records',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['start_time', 'service_type'], name='msc_records_start_t_5eb5ab_idx'), models.Index(fields=['calling_number', 'start_time'], name='msc_records_calling_83a5b3_idx'), models.Index(fields=['called_number', 'start_time'], name='msc_records_called__15f0b9_idx'), models.Index(fields=['imsi', 'start_time'], name='msc_records_imsi_8f4799_idx'), models.Index(fields=['file', 'record_type'], name='msc_records_file_id_b663ba_idx')],
            },
        ),
    ]
