# Generated by Django 4.2.23 on 2026-05-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0002_add_prepaid_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='mscrecord',
            name='forwarded_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mscrecord',
            name='redirecting_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
