# Generated by Django 4.2.23 on 2026-05-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0003_mscrecord_forwarded_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mscrecord',
            name='node_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mscrecord',
            name='tac',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
