# Generated by Django 4.2.23 on 2026-05-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0004_mscrecord_node_id_mscrecord_tac'),
    ]

    operations = [
        migrations.AddField(
            model_name='mscrecord',
            name='call_category',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
