# Generated by Django 4.2.23 on 2026-05-01 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0005_mscrecord_call_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mscrecord',
            name='node_id',
        ),
    ]
