# Generated by Django 4.2.23 on 2026-05-16 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0006_remove_mscrecord_node_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mscrecord',
            name='paired_record',
            field=models.ForeignKey(blank=True, help_text='Linked CDR pair (MOC ↔ MTC record with the same call_reference).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paired_records_reverse', to='msc.mscrecord'),
        ),
    ]
