# Generated by Django 4.2.23 on 2026-05-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0007_mscrecord_paired_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='mscrecord',
            name='smsc_address',
            field=models.CharField(blank=True, db_index=True, help_text='SMSC Global Title (E.164) — populated from SERVICE_CENTRE_ADDRESS for SMSMO/SMSMT records.', max_length=30),
        ),
    ]
