# Generated by Django 4.2.23 on 2026-05-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msc', '0008_mscrecord_smsc_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mscrecord',
            name='roaming_indicator',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
