# Generated by Django 4.2.23 on 2026-09-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrate',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='treatment',
            field=models.CharField(choices=[('EXCLUSIVE', 'Exclusive'), ('INCLUSIVE', 'Inclusive')], default='EXCLUSIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='taxtype',
            name='applicable_operators',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='taxtype',
            name='applicable_services',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
