# Generated by Django 4.2.23 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory', '0002_taxrate_status_taxrate_treatment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcase',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
    ]
