# Generated by Django 4.2.23 on 2026-09-13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('regulatory', '0003_auditcase_resolution_notes')]

    operations = [
        migrations.AddField(
            model_name='tariff', name='is_regulatory_reference',
            field=models.BooleanField(default=False, help_text='Marks this tariff as the NatCA-approved reference rate used for compliance checks.'),
        ),
        migrations.CreateModel(
            name='TariffComplianceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_code', models.SlugField(db_index=True, max_length=30)),
                ('service_type', models.CharField(db_index=True, max_length=10)),
                ('traffic_type', models.CharField(db_index=True, max_length=20)),
                ('tariff_name', models.CharField(max_length=200)),
                ('applied_rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('approved_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('variance_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tolerance_percent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('COMPLIANT', 'Compliant'), ('NON_COMPLIANT', 'Non-Compliant'), ('UNDER_REVIEW', 'Under Review')], db_index=True, max_length=15)),
                ('effective_date', models.DateField(db_index=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('applied_tariff_version', models.PositiveIntegerField()),
                ('approved_tariff_version', models.PositiveIntegerField(blank=True, null=True)),
                ('finding_created', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_results', to='regulatory.tariff')),
                ('approved_tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_compliance_results', to='regulatory.tariff')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('finding_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_results', to='regulatory.auditcase')),
            ],
            options={'db_table': 'regulatory_tariff_compliance_results', 'ordering': ['-last_checked', 'operator_code', 'tariff_name']},
        ),
        migrations.AddConstraint(
            model_name='tariffcomplianceresult',
            constraint=models.UniqueConstraint(fields=('applied_tariff', 'effective_date'), name='unique_tariff_compliance_check'),
        ),
    ]
