# Generated by Django 4.2.23 on 2026-07-24 23:34

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regulatory', '0003_alter_leaextractionlog_executed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveTestCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('test_date', models.DateField(db_index=True)),
                ('region', models.CharField(db_index=True, default='WESTERN_AREA', max_length=80)),
                ('route_description', models.TextField(blank=True, help_text='e.g. Freetown Central - Aberdeen - Lumley Beach Route')),
                ('technology', models.CharField(default='4G', help_text='2G/3G/4G/5G', max_length=10)),
                ('tool_used', models.CharField(default='TEMS', help_text='TEMS, Nemo, SwissQual, XCAL, CSV, etc.', max_length=80)),
                ('operator_name', models.CharField(default='Orange SL', max_length=80)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('ANALYSED', 'Analysed'), ('REPORTED', 'Report Generated')], db_index=True, default='UPLOADED', max_length=12)),
                ('raw_file', models.FileField(blank=True, null=True, upload_to='regulatory/drivetest/')),
                ('file_format', models.CharField(default='csv', help_text='csv, trp, lpg, nmf, zip, tar.gz', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Drive Test Campaign',
                'verbose_name_plural': 'Drive Test Campaigns',
                'db_table': 'reg_drive_campaigns',
                'ordering': ['-test_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NetworkKPIDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique identifier e.g. NET_AVAIL, CSSR, CDR', max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('unit', models.CharField(default='%', help_text='%, Mbps, ms, score', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('natca_threshold', models.DecimalField(decimal_places=2, default=Decimal('95.00'), help_text='Regulatory target threshold set by NatCA', max_digits=10)),
                ('threshold_direction', models.CharField(choices=[('ABOVE', 'Must be Greater/Equal Threshold'), ('BELOW', 'Must be Less/Equal Threshold')], default='ABOVE', max_length=8)),
                ('technology', models.CharField(choices=[('2G', '2G (GSM)'), ('3G', '3G (UMTS)'), ('4G', '4G (LTE)'), ('5G', '5G (NR)'), ('ALL', 'All Technologies / Composite')], default='ALL', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Network KPI Definition',
                'verbose_name_plural': 'Network KPI Definitions',
                'db_table': 'reg_kpi_definitions',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='NetworkKPIImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(default='MANUAL', max_length=20)),
                ('record_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='COMPLETED', max_length=20)),
                ('errors_json', models.JSONField(blank=True, default=list)),
                ('imported_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Network KPI Import Log',
                'verbose_name_plural': 'Network KPI Import Logs',
                'db_table': 'reg_kpi_import_logs',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='DriveTestSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('rsrp', models.DecimalField(blank=True, decimal_places=2, help_text='RSRP in dBm', max_digits=7, null=True)),
                ('rsrq', models.DecimalField(blank=True, decimal_places=2, help_text='RSRQ in dB', max_digits=7, null=True)),
                ('sinr', models.DecimalField(blank=True, decimal_places=2, help_text='SINR in dB', max_digits=7, null=True)),
                ('dl_throughput', models.DecimalField(blank=True, decimal_places=2, help_text='DL Throughput (Mbps)', max_digits=8, null=True)),
                ('ul_throughput', models.DecimalField(blank=True, decimal_places=2, help_text='UL Throughput (Mbps)', max_digits=8, null=True)),
                ('cssr_status', models.BooleanField(blank=True, help_text='True=Call Setup Success, False=Failure', null=True)),
                ('drop_status', models.BooleanField(blank=True, help_text='True=Call Dropped, False=Normal', null=True)),
                ('handover_status', models.BooleanField(blank=True, help_text='True=Handover Success, False=Failure', null=True)),
                ('ping_rtt', models.DecimalField(blank=True, decimal_places=2, help_text='Ping RTT in ms', max_digits=8, null=True)),
                ('voice_mos', models.DecimalField(blank=True, decimal_places=2, help_text='Voice MOS score 1.0-5.0', max_digits=4, null=True)),
                ('technology', models.CharField(default='4G', max_length=10)),
                ('cell_id', models.CharField(blank=True, max_length=40)),
                ('pci', models.IntegerField(blank=True, null=True)),
                ('earfcn', models.IntegerField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='regulatory.drivetestcampaign')),
            ],
            options={
                'verbose_name': 'Drive Test Sample',
                'verbose_name_plural': 'Drive Test Samples',
                'db_table': 'reg_drive_samples',
                'ordering': ['timestamp', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DriveTestAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_samples', models.IntegerField(default=0)),
                ('coverage_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('avg_rsrp', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('avg_rsrq', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('avg_sinr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('avg_dl_throughput', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('avg_ul_throughput', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('cssr_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('drop_rate_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('handover_sr_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('avg_ping_rtt', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('avg_voice_mos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4)),
                ('natca_compliant', models.BooleanField(default=False)),
                ('analysis_json', models.JSONField(blank=True, default=dict)),
                ('analysed_at', models.DateTimeField(auto_now=True)),
                ('analysed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='regulatory.drivetestcampaign')),
            ],
            options={
                'verbose_name': 'Drive Test Analysis',
                'verbose_name_plural': 'Drive Test Analyses',
                'db_table': 'reg_drive_analysis',
            },
        ),
        migrations.CreateModel(
            name='NetworkKPIEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_date', models.DateField(db_index=True)),
                ('granularity', models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], db_index=True, default='DAILY', max_length=8)),
                ('region', models.CharField(db_index=True, default='NATIONAL', max_length=80)),
                ('cell_id', models.CharField(blank=True, help_text='Optional specific cell/node ID', max_length=80)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('is_compliant', models.BooleanField(db_index=True, default=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('CSV_IMPORT', 'CSV/File Import'), ('SFTP', 'SFTP Automated Sync'), ('API', 'REST API Push')], default='MANUAL', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_log', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='regulatory.networkkpiimportlog')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='regulatory.networkkpidefinition')),
            ],
            options={
                'verbose_name': 'Network KPI Entry',
                'verbose_name_plural': 'Network KPI Entries',
                'db_table': 'reg_kpi_entries',
                'ordering': ['-period_date', 'kpi__code', 'region'],
                'unique_together': {('kpi', 'period_date', 'granularity', 'region', 'cell_id')},
            },
        ),
    ]
