# Generated by Django 4.2.23 on 2026-09-13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('regulatory', '0004_tariff_regulatory_reference_and_compliance')]

    operations = [
        migrations.AddField(model_name='taxtype', name='category', field=models.CharField(choices=[('GST', 'GST'), ('EXCISE', 'Excise'), ('IMPORT', 'Import'), ('LEVY', 'Levy'), ('REGULATORY', 'Regulatory'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=15)),
        migrations.AddField(model_name='taxtype', name='updated_at', field=models.DateTimeField(auto_now=True)),
        migrations.AddField(model_name='taxrate', name='created_by', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name='taxrate', name='version', field=models.PositiveIntegerField(default=1)),
        migrations.AlterField(model_name='taxrate', name='status', field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SCHEDULED', 'Scheduled'), ('EXPIRED', 'Expired'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
        migrations.AlterModelOptions(name='taxrate', options={'ordering': ['tax_type', '-version']}),
    ]
