# Generated by Django 4.2.23 on 2026-09-13 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regulatory', '0005_tax_versioning_and_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclarationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='regulatory/declarations/%Y/%m/')),
                ('document_type', models.CharField(default='SUPPORTING_DOCUMENT', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'regulatory_declaration_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DeclarationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VALIDATED', 'Validated'), ('REVIEW_STARTED', 'Review Started'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CLARIFICATION', 'Clarification Requested'), ('RECONCILED', 'Reconciled')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'regulatory_declaration_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='operatordeclaration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operatordeclaration',
            name='declaration_type',
            field=models.CharField(choices=[('GST', 'GST'), ('REVENUE', 'Revenue'), ('GST_REVENUE', 'GST + Revenue'), ('INTERNATIONAL_REVENUE', 'International Revenue'), ('ROAMING_REVENUE', 'Roaming Revenue'), ('INTERCONNECT_REVENUE', 'Interconnect Revenue')], default='GST_REVENUE', max_length=30),
        ),
        migrations.AddField(
            model_name='operatordeclaration',
            name='declared_taxable_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='operatordeclaration',
            name='interconnect_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='operatordeclaration',
            name='international_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='operatordeclaration',
            name='is_current_version',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='operatordeclaration',
            name='other_taxable_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='operatordeclaration',
            name='parent_declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='regulatory.operatordeclaration'),
        ),
        migrations.AddField(
            model_name='operatordeclaration',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='operatordeclaration',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='operatordeclaration',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='operatordeclaration',
            name='roaming_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='operatordeclaration',
            name='validation_findings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='operatordeclaration',
            name='validation_result',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='operatordeclaration',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='operatordeclaration',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VALIDATION', 'Validation'), ('UNDER_REVIEW', 'Under Review'), ('ACCEPTED', 'Accepted'), ('RECONCILED', 'Reconciled'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed'), ('VERIFIED', 'Verified (legacy)'), ('DISPUTED', 'Disputed (legacy)')], db_index=True, default='DRAFT', max_length=15),
        ),
        migrations.AddConstraint(
            model_name='operatordeclaration',
            constraint=models.UniqueConstraint(fields=('operator_code', 'period_start', 'period_end', 'declaration_type', 'version'), name='unique_declaration_version'),
        ),
        migrations.AddField(
            model_name='declarationreview',
            name='declaration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='regulatory.operatordeclaration'),
        ),
        migrations.AddField(
            model_name='declarationreview',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='declarationattachment',
            name='declaration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='regulatory.operatordeclaration'),
        ),
        migrations.AddField(
            model_name='declarationattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
