# Generated by Django 4.2.23 on 2026-07-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory', '0005_seed_natca_kpis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networkkpientry',
            options={'ordering': ['-period_date', 'kpi__code', 'operator_code', 'region', 'district'], 'verbose_name': 'Network KPI Entry', 'verbose_name_plural': 'Network KPI Entries'},
        ),
        migrations.AlterUniqueTogether(
            name='networkkpientry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='drivetestcampaign',
            name='district',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='drivetestcampaign',
            name='operator_code',
            field=models.CharField(db_index=True, default='orange', max_length=30),
        ),
        migrations.AddField(
            model_name='networkkpientry',
            name='district',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='networkkpientry',
            name='operator_code',
            field=models.CharField(db_index=True, default='orange', help_text='orange, africell, qcell, sierratel, onemobile, ALL', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='networkkpientry',
            unique_together={('kpi', 'period_date', 'granularity', 'operator_code', 'region', 'district', 'cell_id')},
        ),
    ]
