# Generated by Django 4.2.23 on 2026-07-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory', '0006_alter_networkkpientry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkCellSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_code', models.CharField(db_index=True, default='orange', help_text='orange, africell, qcell, sierratel, onemobile', max_length=30)),
                ('site_id', models.CharField(db_index=True, help_text='Operator Site Identifier e.g. FTW001', max_length=80)),
                ('site_name', models.CharField(help_text='Site Name e.g. Lumley Beach Tower', max_length=160)),
                ('cell_id', models.CharField(blank=True, db_index=True, help_text='Specific Sector / Cell Identifier', max_length=80)),
                ('technology', models.CharField(default='4G', help_text='2G/3G/4G/5G', max_length=10)),
                ('region', models.CharField(db_index=True, default='WESTERN_AREA', max_length=80)),
                ('district', models.CharField(blank=True, db_index=True, max_length=80)),
                ('chiefdom_town', models.CharField(blank=True, help_text='Chiefdom / City / Town', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('height_m', models.DecimalField(blank=True, decimal_places=2, help_text='Tower height in meters', max_digits=6, null=True)),
                ('azimuth', models.IntegerField(blank=True, help_text='Antenna direction 0-360 degrees', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PLANNED', 'Planned')], db_index=True, default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cell Site & Geo Inventory',
                'verbose_name_plural': 'Cell Site & Geo Inventories',
                'db_table': 'reg_cell_sites',
                'ordering': ['operator_code', 'region', 'district', 'site_id'],
                'unique_together': {('operator_code', 'site_id', 'cell_id')},
            },
        ),
    ]
