# Generated by Django 4.2.23 on 2026-09-13 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory', '0006_declaration_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationrun',
            name='declared_gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='declared_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='declared_taxable_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='expected_gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='expected_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='expected_taxable_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='gst_variance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='previous_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reruns', to='regulatory.reconciliationrun'),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='revenue_variance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='risk_level',
            field=models.CharField(default='MATCHED', max_length=10),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='taxable_revenue_variance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='tolerance_percent',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reconciliationrun',
            name='level',
            field=models.CharField(choices=[('TRAFFIC', 'Traffic'), ('REVENUE', 'Revenue'), ('TAXABLE_REVENUE', 'Taxable Revenue'), ('GST', 'GST'), ('FULL', 'Full Reconciliation'), ('MONTHLY', 'Monthly (legacy)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reconciliationrun',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('WARNING', 'Completed with Warnings'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
    ]
