# Generated by Django 4.2.23 on 2026-09-13 12:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regulatory', '0007_reconciliation_run_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskalert',
            name='alert_type',
            field=models.CharField(choices=[('TAX', 'Tax'), ('GST', 'GST'), ('REVENUE', 'Revenue'), ('DATA_QUALITY', 'Data Quality'), ('COMPLIANCE', 'Compliance'), ('TARIFF', 'Tariff'), ('TRAFFIC', 'Traffic'), ('DECLARATION', 'Declaration'), ('RECONCILIATION', 'Reconciliation'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='assignment_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='audit_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_alerts', to='regulatory.auditcase'),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='confirmed_exposure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='dismissal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='dismissal_reason',
            field=models.CharField(blank=True, choices=[('DUPLICATE', 'Duplicate Alert'), ('FALSE_POSITIVE', 'False Positive'), ('INSUFFICIENT_EVIDENCE', 'Insufficient Evidence'), ('WITHIN_TOLERANCE', 'Within Approved Tolerance'), ('OTHER', 'Other')], max_length=25),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='dismissed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='investigation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='investigation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='investigator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='occurrence_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='operator_request_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='operator_request_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='operator_request_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='operator_request_evidence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='operator_request_subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='operator_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='operator_response_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='operator_response_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='potential_exposure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='priority',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='recovered_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=24, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='resolution_type',
            field=models.CharField(blank=True, choices=[('NO_ISSUE', 'No Issue'), ('OPERATOR_CORRECTED', 'Operator Corrected'), ('DATA_ISSUE_CORRECTED', 'Data Issue Corrected'), ('DECLARATION_AMENDED', 'Declaration Amended'), ('TAX_ADJUSTMENT', 'Tax Adjustment'), ('TARIFF_CORRECTED', 'Tariff Corrected'), ('SYSTEM_FALSE_POSITIVE', 'System False Positive'), ('OTHER', 'Other')], max_length=25),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='rule_version',
            field=models.PositiveIntegerField(blank=True, help_text='RiskRule.version active when this alert was triggered', null=True),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='service',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='source_reference',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='source_type',
            field=models.CharField(choices=[('RECONCILIATION', 'Reconciliation'), ('GST_ENGINE', 'GST Engine'), ('REVENUE_ASSURANCE', 'Revenue Assurance'), ('TARIFF_COMPLIANCE', 'Tariff Compliance'), ('OPERATOR_DECLARATIONS', 'Operator Declarations'), ('MEDIATION_DATA_QUALITY', 'Mediation Data Quality'), ('TRAFFIC_MONITORING', 'Traffic Monitoring'), ('MANUAL_RULE', 'Manual Rule'), ('AUDIT_FINDING', 'Audit Finding')], default='MANUAL_RULE', max_length=40),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='threshold_unit',
            field=models.CharField(default='COUNT', max_length=20),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='traffic_type',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='riskrule',
            name='alert_type',
            field=models.CharField(choices=[('TAX', 'Tax'), ('GST', 'GST'), ('REVENUE', 'Revenue'), ('DATA_QUALITY', 'Data Quality'), ('COMPLIANCE', 'Compliance'), ('TARIFF', 'Tariff'), ('TRAFFIC', 'Traffic'), ('DECLARATION', 'Declaration'), ('RECONCILIATION', 'Reconciliation'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AddField(
            model_name='riskrule',
            name='auto_create_alert',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='riskrule',
            name='auto_escalate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riskrule',
            name='code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='riskrule',
            name='comparison_operator',
            field=models.CharField(choices=[('GT', '>'), ('GTE', '>='), ('LT', '<'), ('LTE', '<='), ('EQ', '='), ('NE', '!='), ('PCT_VARIANCE', '% variance greater than'), ('ABS_VARIANCE', 'absolute variance greater than')], default='GT', max_length=15),
        ),
        migrations.AddField(
            model_name='riskrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskrule',
            name='effective_from',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='riskrule',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskrule',
            name='escalation_threshold',
            field=models.PositiveIntegerField(blank=True, help_text='Occurrence count that triggers auto audit-case escalation', null=True),
        ),
        migrations.AddField(
            model_name='riskrule',
            name='lookback_period',
            field=models.PositiveIntegerField(blank=True, help_text='Days of history to evaluate', null=True),
        ),
        migrations.AddField(
            model_name='riskrule',
            name='min_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Minutes the condition must persist', null=True),
        ),
        migrations.AddField(
            model_name='riskrule',
            name='min_occurrences',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskrule',
            name='service_scope',
            field=models.CharField(blank=True, help_text='Blank = applies to all services', max_length=60),
        ),
        migrations.AddField(
            model_name='riskrule',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='riskrule',
            name='threshold_unit',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('COUNT', 'Count'), ('CURRENCY', 'Currency'), ('DURATION', 'Duration'), ('RATE', 'Rate'), ('RATIO', 'Ratio')], default='COUNT', max_length=20),
        ),
        migrations.AddField(
            model_name='riskrule',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='riskalert',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('INVESTIGATING', 'Investigating'), ('UNDER_REVIEW', 'Under Review'), ('AWAITING_OPERATOR', 'Awaiting Operator'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=18),
        ),
        migrations.AlterField(
            model_name='riskrule',
            name='rule_type',
            field=models.CharField(choices=[('THRESHOLD', 'Threshold'), ('ANOMALY', 'Anomaly Detection'), ('TREND', 'Trend Analysis')], default='THRESHOLD', max_length=12),
        ),
        migrations.CreateModel(
            name='RiskAlertComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='regulatory.riskalert')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'regulatory_risk_alert_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskRuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('alert_type', models.CharField(max_length=30)),
                ('metric', models.CharField(max_length=100)),
                ('comparison_operator', models.CharField(max_length=15)),
                ('threshold_value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('threshold_unit', models.CharField(max_length=20)),
                ('severity', models.CharField(max_length=10)),
                ('operator_code', models.SlugField(blank=True, max_length=30)),
                ('service_scope', models.CharField(blank=True, max_length=60)),
                ('description', models.TextField(blank=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='regulatory.riskrule')),
            ],
            options={
                'db_table': 'regulatory_risk_rule_versions',
                'ordering': ['-version'],
                'unique_together': {('rule', 'version')},
            },
        ),
    ]
