# Generated by Django 4.2.23 on 2026-07-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory', '0007_networkcellsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkCounterDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_id', models.CharField(db_index=True, help_text='Vendor Counter Code e.g. L.RRC.ConnReq.Att', max_length=100)),
                ('counter_name', models.CharField(help_text='Full Counter Description', max_length=200)),
                ('vendor', models.CharField(db_index=True, default='Huawei', help_text='Huawei, Ericsson, ZTE, Nokia, etc.', max_length=50)),
                ('network_element', models.CharField(db_index=True, default='eNodeB', help_text='MSC, IMS, PGW, eNodeB, gNodeB, etc.', max_length=50)),
                ('technology', models.CharField(db_index=True, default='4G', help_text='2G/3G/4G/5G', max_length=10)),
                ('kpi_code', models.CharField(blank=True, db_index=True, help_text='Mapped PM KPI code e.g. CSSR, CDR', max_length=40)),
                ('formula_role', models.CharField(choices=[('NUMERATOR', 'Numerator (Events/Successes)'), ('DENOMINATOR', 'Denominator (Attempts/Total)'), ('MEASURED', 'Direct Measured Value'), ('VALUE', 'Raw Gauge / Count Value')], default='NUMERATOR', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Counter Dictionary Entry',
                'verbose_name_plural': 'Counter Dictionary Entries',
                'db_table': 'reg_counter_dictionary',
                'ordering': ['vendor', 'network_element', 'counter_id'],
                'unique_together': {('vendor', 'network_element', 'counter_id')},
            },
        ),
    ]
