# Generated by Django 4.2.23 on 2026-07-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory', '0008_networkcounterdefinition'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkcellsite',
            name='bsc_rnc_name',
            field=models.CharField(blank=True, help_text='BSC / RNC / MME Name e.g. HW_FTBSC02', max_length=100),
        ),
        migrations.AddField(
            model_name='networkcellsite',
            name='bts_enodeb_id',
            field=models.CharField(blank=True, help_text='BTS / eNodeB ID e.g. 2001', max_length=80),
        ),
        migrations.AddField(
            model_name='networkcellsite',
            name='cell_name',
            field=models.CharField(blank=True, help_text='Cell Name e.g. 2G_WILBERFORCE-11', max_length=160),
        ),
        migrations.AddField(
            model_name='networkcellsite',
            name='cgi_ecgi',
            field=models.CharField(blank=True, db_index=True, help_text='Cell Global Identity e.g. 619012011810011', max_length=40),
        ),
        migrations.AddField(
            model_name='networkcellsite',
            name='chiefdom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='networkcellsite',
            name='classification',
            field=models.CharField(blank=True, help_text='Platinum, Gold, Silver', max_length=50),
        ),
        migrations.AddField(
            model_name='networkcellsite',
            name='lac_tac',
            field=models.CharField(blank=True, help_text='Location Area Code / Tracking Area Code', max_length=20),
        ),
        migrations.AddField(
            model_name='networkcellsite',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='networkcellsite',
            name='mcc',
            field=models.CharField(default='619', max_length=5),
        ),
        migrations.AddField(
            model_name='networkcellsite',
            name='mnc',
            field=models.CharField(default='01', max_length=5),
        ),
        migrations.AddField(
            model_name='networkcellsite',
            name='natca_classification',
            field=models.CharField(blank=True, db_index=True, help_text='Urban Area, Rural Area', max_length=50),
        ),
        migrations.AddField(
            model_name='networkcellsite',
            name='ne_name',
            field=models.CharField(blank=True, help_text='Network Element Name e.g. SL0001_WILBERFORCE', max_length=160),
        ),
        migrations.AddField(
            model_name='networkcellsite',
            name='on_air_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkcellsite',
            name='site_owner',
            field=models.CharField(blank=True, help_text='Owner / Towerco info', max_length=120),
        ),
        migrations.AddField(
            model_name='networkcellsite',
            name='site_type',
            field=models.CharField(blank=True, help_text='Greenfield, Rooftop', max_length=50),
        ),
        migrations.AlterField(
            model_name='networkcellsite',
            name='cell_id',
            field=models.CharField(blank=True, db_index=True, help_text='Specific Sector / Cell Identifier e.g. 10011', max_length=80),
        ),
        migrations.AlterField(
            model_name='networkcellsite',
            name='chiefdom_town',
            field=models.CharField(blank=True, help_text='Legacy town/city field', max_length=100),
        ),
        migrations.AlterField(
            model_name='networkcellsite',
            name='region',
            field=models.CharField(db_index=True, default='Western Area', max_length=80),
        ),
        migrations.AlterField(
            model_name='networkcellsite',
            name='site_id',
            field=models.CharField(db_index=True, help_text='Operator Site Identifier e.g. SL0001', max_length=80),
        ),
        migrations.AlterField(
            model_name='networkcellsite',
            name='site_name',
            field=models.CharField(help_text='Site Name e.g. SL0001_WILBERFORCE', max_length=160),
        ),
        migrations.AlterField(
            model_name='networkcellsite',
            name='technology',
            field=models.CharField(db_index=True, default='4G', help_text='2G, 3G, 4G, 5G, 2G3G4G, 2G_HUAWEI, etc.', max_length=30),
        ),
    ]
