# Generated by Django 4.2.23 on 2026-09-13 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regulatory', '0008_risk_alerts_rebuild'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditevidence',
            options={'ordering': ['case', '-created_at'], 'verbose_name_plural': 'Audit evidence'},
        ),
        migrations.RemoveField(
            model_name='auditcase',
            name='resolution_notes',
        ),
        migrations.RemoveField(
            model_name='auditcase',
            name='total_amount_at_risk',
        ),
        migrations.RemoveField(
            model_name='auditfinding',
            name='amount_at_risk',
        ),
        migrations.RemoveField(
            model_name='auditfinding',
            name='evidence_summary',
        ),
        migrations.AddField(
            model_name='auditcase',
            name='adjustment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='assignment_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='case_type',
            field=models.CharField(choices=[('GST_VARIANCE', 'GST Variance'), ('REVENUE_VARIANCE', 'Revenue Variance'), ('TAXABLE_REVENUE_VARIANCE', 'Taxable Revenue Variance'), ('MISSING_CDRS', 'Missing CDRs'), ('TARIFF_VIOLATION', 'Tariff Violation'), ('TAX_CLASSIFICATION', 'Tax Classification'), ('DECLARATION_DISCREPANCY', 'Declaration Discrepancy'), ('DATA_QUALITY', 'Data Quality'), ('TRAFFIC_ANOMALY', 'Traffic Anomaly'), ('REPEATED_COMPLIANCE_FAILURE', 'Repeated Compliance Failure'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='closure_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='confirmed_exposure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_cases', to='regulatory.operatordeclaration'),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='finding_summary',
            field=models.CharField(blank=True, help_text='One-line finding shown in the case list', max_length=255),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='follow_up_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='investigation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='investigation_started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='potential_exposure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='priority',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='reconciliation_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_cases', to='regulatory.reconciliationrun'),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='recovered_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='reopen_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='reopen_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='resolution_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='resolution_type',
            field=models.CharField(blank=True, choices=[('NO_ISSUE', 'No Issue'), ('OPERATOR_CORRECTION', 'Operator Correction'), ('DECLARATION_AMENDED', 'Declaration Amended'), ('TAX_ADJUSTMENT', 'Tax Adjustment'), ('TARIFF_CORRECTED', 'Tariff Corrected'), ('DATA_ISSUE', 'Data Issue'), ('REVENUE_RECOVERED', 'Revenue Recovered'), ('COMPLIANCE_ACTION', 'Compliance Action'), ('OTHER', 'Other')], max_length=25),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='risk_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_audit_cases', to='regulatory.riskalert'),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='tariff_compliance_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_audit_cases', to='regulatory.tariffcomplianceresult'),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='auditevidence',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='regulatory.auditcase'),
        ),
        migrations.AddField(
            model_name='auditevidence',
            name='checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditevidence',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditevidence',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditevidence',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='regulatory/audit_evidence/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='auditevidence',
            name='source_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='expected_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='financial_exposure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='observed_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='recommendation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CONFIRMED', 'Confirmed'), ('DISPUTED', 'Disputed'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=10),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='variance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='auditcase',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('INVESTIGATION', 'Investigation'), ('AWAITING_OPERATOR', 'Awaiting Operator'), ('OPERATOR_RESPONSE', 'Operator Response'), ('REGULATORY_REVIEW', 'Regulatory Review'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditevidence',
            name='evidence_type',
            field=models.CharField(choices=[('RISK_ALERT', 'Risk Alert'), ('RECONCILIATION', 'Reconciliation Result'), ('OPERATOR_DECLARATION', 'Operator Declaration'), ('TARIFF_COMPLIANCE', 'Tariff Compliance Result'), ('REVENUE_CALCULATION', 'Revenue Calculation'), ('GST_CALCULATION', 'GST Calculation'), ('TAX_RULE_VERSION', 'Tax Rule Version'), ('TARIFF_VERSION', 'Tariff Version'), ('CDR_SAMPLE', 'CDR Sample'), ('SOURCE_FILE', 'Source File'), ('DOCUMENT', 'Uploaded Document'), ('SCREENSHOT', 'Screenshot'), ('ANALYST_NOTE', 'Analyst Note'), ('TRAFFIC_SUMMARY', 'Traffic Summary')], max_length=25),
        ),
        migrations.AlterField(
            model_name='auditevidence',
            name='finding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_items', to='regulatory.auditfinding'),
        ),
        migrations.AlterField(
            model_name='auditevidence',
            name='reference_id',
            field=models.CharField(blank=True, help_text='PK/identifier of the referenced object (string to avoid cross-model FK)', max_length=100),
        ),
        migrations.CreateModel(
            name='AuditOperatorResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_subject', models.CharField(max_length=200)),
                ('request_details', models.TextField()),
                ('required_evidence', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('response_text', models.TextField(blank=True)),
                ('submitted_by', models.CharField(blank=True, help_text='Operator contact who submitted the response', max_length=150)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('response_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_responses', to='regulatory.auditcase')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'regulatory_audit_operator_responses',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditCaseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('visibility', models.CharField(choices=[('INTERNAL', 'Internal'), ('OPERATOR_VISIBLE', 'Operator-visible')], default='INTERNAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='regulatory.auditcase')),
            ],
            options={
                'db_table': 'regulatory_audit_case_comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
