# Generated by Django 4.2.23 on 2026-09-13 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory', '0009_audit_cases_rebuild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevidence',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='regulatory.auditcase'),
        ),
    ]
