# Generated by Django 4.2.23 on 2026-07-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory', '0009_networkcellsite_bsc_rnc_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkSectorCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_code', models.CharField(db_index=True, default='orange', max_length=30)),
                ('site_id', models.CharField(db_index=True, help_text='Parent Physical Site ID e.g. SL0001', max_length=80)),
                ('bts_name', models.CharField(blank=True, help_text='BTS Name e.g. 2G_WILBERFORCE', max_length=160)),
                ('ne_name', models.CharField(blank=True, help_text='NE Name e.g. SL0001_WILBERFORCE', max_length=160)),
                ('cell_name', models.CharField(db_index=True, help_text='Cell Name e.g. 2G_WILBERFORCE-11', max_length=160)),
                ('local_cell_id', models.IntegerField(blank=True, help_text='Local Cell ID e.g. 1', null=True)),
                ('bts_enodeb_id', models.CharField(blank=True, help_text='BTS ID / eNodeB ID e.g. 2001', max_length=80)),
                ('mcc', models.CharField(default='619', max_length=5)),
                ('mnc', models.CharField(default='01', max_length=5)),
                ('lac_tac', models.CharField(blank=True, max_length=20)),
                ('cell_id', models.CharField(db_index=True, help_text='Cell ID e.g. 10011', max_length=80)),
                ('cgi_ecgi', models.CharField(db_index=True, help_text='CGI e.g. 619012011810011', max_length=40)),
                ('bsc_rnc_name', models.CharField(blank=True, help_text='BSC Name e.g. HW_FTBSC02', max_length=100)),
                ('technology', models.CharField(db_index=True, default='4G', help_text='2G_HUAWEI, 3G_HUAWEI, 4G_HUAWEI, 5G_HUAWEI', max_length=30)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('status', models.CharField(db_index=True, default='ACTIVE', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sector Cell Inventory',
                'verbose_name_plural': 'Sector Cell Inventories',
                'db_table': 'reg_sector_cells',
                'ordering': ['operator_code', 'site_id', 'cell_id'],
                'unique_together': {('operator_code', 'site_id', 'cell_id')},
            },
        ),
    ]
