# Generated by Django 4.2.23 on 2026-07-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory', '0010_networksectorcell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkkpientry',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
