# Generated by Django 4.2.23 on 2026-09-13 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regulatory', '0010_audit_evidence_case_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskalert',
            name='operator_request_at',
        ),
        migrations.RemoveField(
            model_name='riskalert',
            name='operator_request_details',
        ),
        migrations.RemoveField(
            model_name='riskalert',
            name='operator_request_due_date',
        ),
        migrations.RemoveField(
            model_name='riskalert',
            name='operator_request_evidence',
        ),
        migrations.RemoveField(
            model_name='riskalert',
            name='operator_request_subject',
        ),
        migrations.RemoveField(
            model_name='riskalert',
            name='operator_response_at',
        ),
        migrations.RemoveField(
            model_name='riskalert',
            name='operator_response_by',
        ),
        migrations.RemoveField(
            model_name='riskalert',
            name='operator_response_text',
        ),
        migrations.CreateModel(
            name='RiskAlertOperatorResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_subject', models.CharField(max_length=200)),
                ('request_details', models.TextField()),
                ('required_evidence', models.TextField(blank=True)),
                ('priority', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('response_text', models.TextField(blank=True)),
                ('submitted_by', models.CharField(blank=True, help_text='Operator contact who submitted the response', max_length=150)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('response_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_responses', to='regulatory.riskalert')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'regulatory_risk_alert_operator_responses',
                'ordering': ['-requested_at'],
            },
        ),
    ]
