# Generated by Django 4.2.23 on 2026-09-13 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regulatory', '0011_risk_alert_investigation_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcase',
            name='regulatory_decision',
            field=models.CharField(blank=True, choices=[('NO_FURTHER_ACTION', 'No Further Action'), ('OPERATOR_CORRECTION_REQUIRED', 'Operator Correction Required'), ('ADDITIONAL_TAX_REVIEW', 'Additional Tax Review Required'), ('ADDITIONAL_REVENUE_REVIEW', 'Additional Revenue Review Required'), ('FORMAL_COMPLIANCE_REVIEW', 'Formal Compliance Review'), ('REFERRAL_FOR_ENFORCEMENT', 'Referral for Enforcement'), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='auditcase',
            name='priority',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='auditcase',
            name='resolution_type',
            field=models.CharField(blank=True, choices=[('NO_ISSUE', 'No Issue'), ('OPERATOR_CORRECTION', 'Operator Correction'), ('DECLARATION_AMENDED', 'Declaration Amended'), ('TAX_ADJUSTMENT', 'Tax Adjustment'), ('REVENUE_RECOVERED', 'Revenue Recovered'), ('TARIFF_CORRECTED', 'Tariff Corrected'), ('DATA_QUALITY_CORRECTED', 'Data Quality Corrected'), ('COMPLIANCE_ACTION', 'Compliance Action'), ('ADMINISTRATIVE_CLOSURE', 'Administrative Closure'), ('OTHER', 'Other')], max_length=25),
        ),
        migrations.CreateModel(
            name='AuditCaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('file_format', models.CharField(default='XLSX', max_length=10)),
                ('file', models.FileField(upload_to='regulatory/audit_reports/%Y/%m/')),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('case_status_at_generation', models.CharField(blank=True, max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='regulatory.auditcase')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'regulatory_audit_case_reports',
                'ordering': ['-version'],
                'unique_together': {('case', 'version')},
            },
        ),
    ]
