# Generated by Django 4.2.23 on 2026-07-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory', '0011_alter_networkkpientry_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkkpiimportlog',
            name='status',
            field=models.CharField(default='COMPLETED', max_length=40),
        ),
    ]
