# Generated by Django 4.2.23 on 2026-07-25 15:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory', '0012_alter_networkkpiimportlog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivetestanalysis',
            name='corridor_segments',
            field=models.JSONField(blank=True, default=list, help_text='Equidistant corridor segment analysis'),
        ),
        migrations.AddField(
            model_name='drivetestanalysis',
            name='pci_pollution_json',
            field=models.JSONField(blank=True, default=dict, help_text='PCI pollution and handover stability metrics'),
        ),
        migrations.AddField(
            model_name='drivetestanalysis',
            name='rsrp_percentiles',
            field=models.JSONField(blank=True, default=dict, help_text='p5, p25, p50, p90, p95 percentiles for RSRP'),
        ),
        migrations.AddField(
            model_name='drivetestanalysis',
            name='sinr_percentiles',
            field=models.JSONField(blank=True, default=dict, help_text='p5, p25, p50, p90, p95 percentiles for SINR'),
        ),
        migrations.AddField(
            model_name='drivetestanalysis',
            name='tp_percentiles',
            field=models.JSONField(blank=True, default=dict, help_text='p5, p25, p50, p90, p95 percentiles for Throughput'),
        ),
        migrations.AddField(
            model_name='drivetestcampaign',
            name='cluster_id',
            field=models.CharField(blank=True, db_index=True, help_text='Spatial Cluster Identifier e.g. CL01_FREETOWN', max_length=80),
        ),
        migrations.AddField(
            model_name='drivetestcampaign',
            name='file_size_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drivetestcampaign',
            name='sha256_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash to prevent duplicate file uploads', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='drivetestcampaign',
            name='source_type',
            field=models.CharField(db_index=True, default='FILE_UPLOAD', help_text='FILE_UPLOAD or LIVE_STREAMING', max_length=20),
        ),
        migrations.AddField(
            model_name='drivetestcampaign',
            name='total_distance_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AddField(
            model_name='drivetestsample',
            name='is_blackspot',
            field=models.BooleanField(db_index=True, default=False, help_text='Flagged coverage blackspot (RSRP < -110 dBm)'),
        ),
        migrations.AddField(
            model_name='drivetestsample',
            name='jitter_ms',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Packet Jitter in ms', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='drivetestsample',
            name='neighbor_pci_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='drivetestsample',
            name='packet_loss_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Packet Loss %', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='drivetestsample',
            name='rssi',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='RSSI in dBm', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='drivetestsample',
            name='serving_pci',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
