# Generated by Django 5.2.17 on 2026-09-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulatory", "0013_currency_decimal_2_places"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tariff",
            name="rate",
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name="tariffcomplianceresult",
            name="applied_rate",
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name="tariffcomplianceresult",
            name="approved_rate",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tariffcomplianceresult",
            name="variance",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=14, null=True
            ),
        ),
    ]
