# Generated by Django 5.2.17 on 2026-09-24 20:07

import django.db.models.deletion
import drive_test.models.session
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0009_alter_alertthreshold_metric_alter_systemcontrol_id"),
        ("reference", "0011_alter_sourcepattern_decoder_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceManufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence_num", models.IntegerField()),
                ("captured_at", models.DateTimeField(db_index=True)),
                ("local_timestamp", models.DateTimeField(blank=True, null=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("altitude_m", models.FloatField(blank=True, null=True)),
                ("gps_accuracy_m", models.FloatField(blank=True, null=True)),
                ("gps_hdop", models.FloatField(blank=True, null=True)),
                ("speed_kmh", models.FloatField(blank=True, null=True)),
                ("heading_deg", models.FloatField(blank=True, null=True)),
                ("match_confidence", models.FloatField(blank=True, null=True)),
                ("match_method", models.CharField(blank=True, max_length=30)),
                ("obs_mcc", models.CharField(blank=True, max_length=3)),
                ("obs_mnc", models.CharField(blank=True, max_length=3)),
                ("obs_lac", models.IntegerField(blank=True, null=True)),
                ("obs_ci", models.IntegerField(blank=True, null=True)),
                ("obs_tac", models.IntegerField(blank=True, null=True)),
                ("obs_eci", models.BigIntegerField(blank=True, null=True)),
                ("obs_pci", models.IntegerField(blank=True, null=True)),
                ("obs_earfcn", models.IntegerField(blank=True, null=True)),
                ("obs_nrarfcn", models.IntegerField(blank=True, null=True)),
                ("is_valid", models.BooleanField(default=True)),
                ("quality_flags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["drive_file", "sequence_num"],
            },
        ),
        migrations.CreateModel(
            name="NetworkVendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ParserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("parser_class", models.CharField(max_length=200)),
                ("vendor", models.CharField(blank=True, max_length=100)),
                ("file_extensions", models.JSONField(blank=True, default=list)),
                ("magic_bytes", models.CharField(blank=True, max_length=200)),
                ("header_signature", models.CharField(blank=True, max_length=200)),
                ("default_config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(default="SL", max_length=2)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RegulatoryRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("technology", models.CharField(blank=True, max_length=5)),
                ("service_type", models.CharField(blank=True, max_length=10)),
                ("metric", models.CharField(max_length=50)),
                ("condition", models.CharField(max_length=3)),
                ("regulatory_reference", models.CharField(blank=True, max_length=200)),
                ("authority", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["rule_code"],
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sector_id", models.CharField(max_length=50)),
                ("azimuth_deg", models.FloatField(blank=True, null=True)),
                ("height_m", models.FloatField(blank=True, null=True)),
                ("tilt_deg", models.FloatField(blank=True, null=True)),
                ("electrical_tilt_deg", models.FloatField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["site", "sector_id"],
            },
        ),
        migrations.CreateModel(
            name="Cell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cell_id", models.CharField(max_length=50)),
                (
                    "technology",
                    models.CharField(
                        choices=[
                            ("2G", "2G/GSM"),
                            ("3G", "3G/UMTS"),
                            ("4G", "4G/LTE"),
                            ("5G", "5G/NR"),
                            ("CDMA", "CDMA"),
                        ],
                        max_length=5,
                    ),
                ),
                ("mcc", models.CharField(blank=True, max_length=3)),
                ("mnc", models.CharField(blank=True, max_length=3)),
                ("lac", models.IntegerField(blank=True, null=True)),
                ("rac", models.IntegerField(blank=True, null=True)),
                ("tac", models.IntegerField(blank=True, null=True)),
                ("ci", models.IntegerField(blank=True, null=True)),
                ("eci", models.BigIntegerField(blank=True, null=True)),
                ("nci", models.BigIntegerField(blank=True, null=True)),
                ("pci", models.IntegerField(blank=True, null=True)),
                ("earfcn", models.IntegerField(blank=True, null=True)),
                ("nrarfcn", models.IntegerField(blank=True, null=True)),
                ("cgi", models.CharField(blank=True, db_index=True, max_length=30)),
                ("ecgi", models.CharField(blank=True, db_index=True, max_length=30)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("altitude_m", models.FloatField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("commissioned_date", models.DateField(blank=True, null=True)),
                ("decommissioned_date", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drive_test_cells",
                        to="reference.operator",
                    ),
                ),
            ],
            options={
                "ordering": ["operator", "cell_id"],
            },
        ),
        migrations.CreateModel(
            name="CellHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("change_type", models.CharField(max_length=20)),
                ("snapshot", models.JSONField()),
                (
                    "cell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="drive_test.cell",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="DeviceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("supported_technologies", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="models",
                        to="drive_test.devicemanufacturer",
                    ),
                ),
            ],
            options={
                "unique_together": {("manufacturer", "model_name")},
            },
        ),
        migrations.CreateModel(
            name="Chiefdom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chiefdoms",
                        to="drive_test.district",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DriveTestFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_filename", models.CharField(max_length=500)),
                ("file_path", models.CharField(max_length=1000)),
                ("file_size", models.BigIntegerField()),
                ("sha256", models.CharField(max_length=64, unique=True)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("detected_format", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("PARSING", "Parsing"),
                            ("PARSED", "Parsed"),
                            ("MATCHING", "Cell Matching"),
                            ("NORMALIZING", "Normalizing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("DUPLICATE", "Duplicate"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
                ("measurement_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drive_test_files",
                        to="core.jobrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="DataQualityResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_records", models.IntegerField(default=0)),
                ("valid_records", models.IntegerField(default=0)),
                ("invalid_records", models.IntegerField(default=0)),
                ("missing_gps", models.IntegerField(default=0)),
                ("missing_cell_id", models.IntegerField(default=0)),
                ("missing_signal", models.IntegerField(default=0)),
                ("matched_cells", models.IntegerField(default=0)),
                ("unmatched_cells", models.IntegerField(default=0)),
                ("match_rate_pct", models.FloatField(default=0.0)),
                ("completeness_score", models.FloatField(default=0.0)),
                ("accuracy_score", models.FloatField(default=0.0)),
                ("overall_score", models.FloatField(default=0.0)),
                ("issues", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "drive_file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_result",
                        to="drive_test.drivetestfile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DriveTestSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_ref",
                    models.CharField(
                        default=drive_test.models.session._generate_session_ref,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("test_date", models.DateField()),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("outdoor", "Outdoor Drive Test"),
                            ("indoor", "Indoor Walk Test"),
                            ("benchmarking", "Benchmarking"),
                            ("regulatory", "Regulatory Audit"),
                            ("coverage", "Coverage Survey"),
                            ("other", "Other"),
                        ],
                        default="outdoor",
                        max_length=20,
                    ),
                ),
                ("tester_name", models.CharField(blank=True, max_length=200)),
                ("vehicle_id", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADING", "Uploading"),
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("PARTIAL", "Partial"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("total_measurements", models.IntegerField(default=0)),
                ("matched_measurements", models.IntegerField(default=0)),
                ("finding_count", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drive_test_sessions",
                        to="reference.operator",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_drive_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="drive_test.region",
                    ),
                ),
            ],
            options={
                "ordering": ["-test_date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="drivetestfile",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="drive_test.drivetestsession",
            ),
        ),
        migrations.CreateModel(
            name="FrequencyBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("band_number", models.CharField(max_length=10)),
                (
                    "technology",
                    models.CharField(
                        choices=[
                            ("2G", "2G/GSM"),
                            ("3G", "3G/UMTS"),
                            ("4G", "4G/LTE"),
                            ("5G", "5G/NR"),
                        ],
                        max_length=3,
                    ),
                ),
                ("frequency_mhz", models.FloatField()),
                ("bandwidth_mhz", models.FloatField(blank=True, null=True)),
                ("duplex_mode", models.CharField(blank=True, max_length=10)),
                ("description", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["technology", "band_number"],
                "unique_together": {("band_number", "technology")},
            },
        ),
        migrations.AddField(
            model_name="cell",
            name="band",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cells",
                to="drive_test.frequencyband",
            ),
        ),
        migrations.CreateModel(
            name="RadioMeasurement",
            fields=[
                (
                    "measurement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="radio",
                        serialize=False,
                        to="drive_test.measurement",
                    ),
                ),
                ("technology", models.CharField(blank=True, max_length=5)),
                ("rssi", models.FloatField(blank=True, null=True)),
                ("rscp", models.FloatField(blank=True, null=True)),
                ("ecio", models.FloatField(blank=True, null=True)),
                ("rsrp", models.FloatField(blank=True, null=True)),
                ("rsrq", models.FloatField(blank=True, null=True)),
                ("sinr", models.FloatField(blank=True, null=True)),
                ("cqi", models.IntegerField(blank=True, null=True)),
                ("ss_rsrp", models.FloatField(blank=True, null=True)),
                ("ss_rsrq", models.FloatField(blank=True, null=True)),
                ("ss_sinr", models.FloatField(blank=True, null=True)),
                ("dl_throughput_kbps", models.FloatField(blank=True, null=True)),
                ("ul_throughput_kbps", models.FloatField(blank=True, null=True)),
                ("handover_count", models.IntegerField(default=0)),
                ("ho_success_count", models.IntegerField(default=0)),
                ("ho_failure_count", models.IntegerField(default=0)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddField(
            model_name="measurement",
            name="drive_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="measurements",
                to="drive_test.drivetestfile",
            ),
        ),
        migrations.AddField(
            model_name="measurement",
            name="matched_cell",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="measurements",
                to="drive_test.cell",
            ),
        ),
        migrations.CreateModel(
            name="HandoverEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ho_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("intra_freq", "Intra-frequency"),
                            ("inter_freq", "Inter-frequency"),
                            ("inter_rat", "Inter-RAT"),
                            ("irat_2g", "IRAT to 2G"),
                            ("irat_3g", "IRAT to 3G"),
                            ("irat_4g", "IRAT to 4G"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("ping_pong", "Ping-Pong"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("ho_duration_ms", models.IntegerField(blank=True, null=True)),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "source_cell",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handover_sources",
                        to="drive_test.cell",
                    ),
                ),
                (
                    "target_cell",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handover_targets",
                        to="drive_test.cell",
                    ),
                ),
                (
                    "measurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handovers",
                        to="drive_test.measurement",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at"],
            },
        ),
        migrations.AddField(
            model_name="drivetestfile",
            name="parser_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_files",
                to="drive_test.parserprofile",
            ),
        ),
        migrations.AddField(
            model_name="district",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="districts",
                to="drive_test.region",
            ),
        ),
        migrations.CreateModel(
            name="RegulatoryThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("warning_value", models.FloatField(blank=True, null=True)),
                ("critical_value", models.FloatField()),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regulatory_thresholds",
                        to="reference.operator",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thresholds",
                        to="drive_test.regulatoryrule",
                    ),
                ),
            ],
            options={
                "ordering": ["rule", "operator"],
            },
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "finding_type",
                    models.CharField(
                        choices=[
                            ("COVERAGE_HOLE", "Coverage Hole"),
                            ("WEAK_SIGNAL", "Weak Signal"),
                            ("HIGH_INTERFERENCE", "High Interference"),
                            ("DROP_CALL", "Dropped Call"),
                            ("FAILED_CALL", "Failed Call Setup"),
                            ("POOR_DATA", "Poor Data Service"),
                            ("LOW_THROUGHPUT", "Low Throughput"),
                            ("HIGH_LATENCY", "High Latency"),
                            ("THRESHOLD_BREACH", "Threshold Breach"),
                            ("ANOMALY", "Data Anomaly"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("description", models.TextField()),
                ("measured_value", models.FloatField(blank=True, null=True)),
                ("threshold_value", models.FloatField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cell",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="findings",
                        to="drive_test.cell",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_dt_findings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="drive_test.drivetestsession",
                    ),
                ),
                (
                    "measurement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="findings",
                        to="drive_test.measurement",
                    ),
                ),
                (
                    "threshold",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="findings",
                        to="drive_test.regulatorythreshold",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="cell",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cells",
                to="drive_test.sector",
            ),
        ),
        migrations.CreateModel(
            name="ServiceMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("VOICE", "Voice"),
                            ("SMS", "SMS"),
                            ("DATA", "Data"),
                            ("VIDEO", "Video Streaming"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("DROPPED", "Dropped"),
                            ("BLOCKED", "Blocked"),
                            ("NO_ATTEMPT", "No Attempt"),
                        ],
                        default="SUCCESS",
                        max_length=20,
                    ),
                ),
                ("call_setup_time_ms", models.IntegerField(blank=True, null=True)),
                ("call_duration_s", models.IntegerField(blank=True, null=True)),
                ("mos", models.FloatField(blank=True, null=True)),
                ("throughput_kbps", models.FloatField(blank=True, null=True)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("packet_loss_pct", models.FloatField(blank=True, null=True)),
                ("jitter_ms", models.FloatField(blank=True, null=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "measurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="drive_test.measurement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_id", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                (
                    "site_type",
                    models.CharField(
                        choices=[
                            ("macro", "Macro"),
                            ("micro", "Micro"),
                            ("pico", "Pico"),
                            ("femto", "Femto"),
                            ("indoor", "Indoor"),
                            ("rooftop", "Rooftop"),
                            ("monopole", "Monopole"),
                            ("tower", "Tower"),
                            ("other", "Other"),
                        ],
                        default="macro",
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=500)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("altitude_m", models.FloatField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("commissioned_date", models.DateField(blank=True, null=True)),
                ("decommissioned_date", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chiefdom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sites",
                        to="drive_test.chiefdom",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drive_test_sites",
                        to="reference.operator",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sites",
                        to="drive_test.networkvendor",
                    ),
                ),
            ],
            options={
                "ordering": ["operator", "site_id"],
            },
        ),
        migrations.AddField(
            model_name="sector",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sectors",
                to="drive_test.site",
            ),
        ),
        migrations.CreateModel(
            name="TestDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                ("imei", models.CharField(blank=True, max_length=20)),
                ("label", models.CharField(blank=True, max_length=100)),
                ("sim_msisdn", models.CharField(blank=True, max_length=20)),
                ("sim_imsi", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="drive_test.devicemodel",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_devices",
                        to="reference.operator",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="measurement",
            name="test_device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="measurements",
                to="drive_test.testdevice",
            ),
        ),
        migrations.AddIndex(
            model_name="drivetestfile",
            index=models.Index(fields=["sha256"], name="drive_test__sha256_d7f2a1_idx"),
        ),
        migrations.AddIndex(
            model_name="drivetestfile",
            index=models.Index(
                fields=["session", "status"], name="drive_test__session_9a0c6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="drivetestsession",
            index=models.Index(
                fields=["operator", "test_date"], name="drive_test__operato_e52775_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="drivetestsession",
            index=models.Index(fields=["status"], name="drive_test__status_5bb890_idx"),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["session", "severity"], name="drive_test__session_f800a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["is_resolved"], name="drive_test__is_reso_058474_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cell",
            index=models.Index(
                fields=["operator", "mcc", "mnc", "lac", "ci"],
                name="drive_test__operato_779209_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cell",
            index=models.Index(
                fields=["operator", "mcc", "mnc", "tac", "eci"],
                name="drive_test__operato_171355_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cell",
            index=models.Index(
                fields=["latitude", "longitude"], name="drive_test__latitud_b82e3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cell",
            index=models.Index(
                fields=["pci", "earfcn"], name="drive_test__pci_42280a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cell",
            unique_together={("operator", "cell_id")},
        ),
        migrations.AddIndex(
            model_name="servicemeasurement",
            index=models.Index(
                fields=["measurement", "service_type"],
                name="drive_test__measure_eee3d7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="site",
            index=models.Index(
                fields=["operator", "site_id"], name="drive_test__operato_942138_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="site",
            index=models.Index(
                fields=["latitude", "longitude"], name="drive_test__latitud_d2dea1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="site",
            unique_together={("operator", "site_id")},
        ),
        migrations.AlterUniqueTogether(
            name="sector",
            unique_together={("site", "sector_id")},
        ),
        migrations.AddIndex(
            model_name="measurement",
            index=models.Index(
                fields=["drive_file", "sequence_num"],
                name="drive_test__drive_f_b9c057_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="measurement",
            index=models.Index(
                fields=["captured_at"], name="drive_test__capture_ac2c37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="measurement",
            index=models.Index(
                fields=["matched_cell"], name="drive_test__matched_657573_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="measurement",
            index=models.Index(
                fields=["latitude", "longitude"], name="drive_test__latitud_e5fbc3_idx"
            ),
        ),
    ]
