# Generated by Django 4.2.30 on 2026-09-29 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reference", "0011_alter_sourcepattern_decoder_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0009_alter_alertthreshold_metric_alter_systemcontrol_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "technology",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GSM", "2G (GSM)"),
                            ("UMTS", "3G (UMTS)"),
                            ("LTE", "4G (LTE)"),
                            ("NR", "5G (NR)"),
                        ],
                        max_length=8,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "device",
                    models.CharField(
                        blank=True, help_text="Vehicle / test device", max_length=120
                    ),
                ),
                ("tester", models.CharField(blank=True, max_length=120)),
                ("region", models.CharField(blank=True, max_length=120)),
                ("district", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dt_campaigns_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dt_campaigns",
                        to="reference.operator",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Cell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "technology",
                    models.CharField(
                        choices=[
                            ("GSM", "2G (GSM)"),
                            ("UMTS", "3G (UMTS)"),
                            ("LTE", "4G (LTE)"),
                            ("NR", "5G (NR)"),
                        ],
                        db_index=True,
                        max_length=8,
                    ),
                ),
                (
                    "cell_id",
                    models.CharField(
                        db_index=True, help_text="ECI / NCI / CI / UC-Id", max_length=40
                    ),
                ),
                ("site_name", models.CharField(blank=True, max_length=120)),
                ("pci", models.IntegerField(blank=True, null=True)),
                ("psc", models.IntegerField(blank=True, null=True)),
                ("bsic", models.IntegerField(blank=True, null=True)),
                ("earfcn", models.IntegerField(blank=True, null=True)),
                ("uarfcn", models.IntegerField(blank=True, null=True)),
                ("arfcn", models.IntegerField(blank=True, null=True)),
                ("nrarfcn", models.IntegerField(blank=True, null=True)),
                ("band", models.CharField(blank=True, max_length=20)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("azimuth", models.FloatField(blank=True, null=True)),
                ("beamwidth", models.FloatField(blank=True, null=True)),
                ("height_m", models.FloatField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        blank=True, help_text="e.g. CM dump, manual", max_length=60
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dt_cells",
                        to="reference.operator",
                    ),
                ),
            ],
            options={
                "ordering": ["operator", "technology", "cell_id"],
            },
        ),
        migrations.CreateModel(
            name="DriveTestFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("stored_path", models.CharField(blank=True, max_length=1024)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, db_index=True, max_length=64)),
                ("detected_format", models.CharField(blank=True, max_length=40)),
                ("detected_operator", models.CharField(blank=True, max_length=60)),
                (
                    "detected_technology",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GSM", "2G (GSM)"),
                            ("UMTS", "3G (UMTS)"),
                            ("LTE", "4G (LTE)"),
                            ("NR", "5G (NR)"),
                        ],
                        max_length=8,
                    ),
                ),
                ("gps_available", models.BooleanField(blank=True, null=True)),
                ("sample_count", models.IntegerField(blank=True, null=True)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "Not validated"),
                            ("VALID", "Valid"),
                            ("WARNING", "Valid with warnings"),
                            ("INVALID", "Invalid"),
                        ],
                        default="UNKNOWN",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROFILING", "Profiling"),
                            ("READY", "Ready"),
                            ("QUEUED", "Queued"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("DUPLICATE", "Duplicate"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="drive_test.campaign",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dt_files",
                        to="core.jobrecord",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dt_files_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("region", models.CharField(blank=True, max_length=120)),
                ("district", models.CharField(blank=True, max_length=120)),
                ("technologies", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dt_projects_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operators",
                    models.ManyToManyField(
                        blank=True, related_name="dt_projects", to="reference.operator"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("geometry", models.JSONField(blank=True, default=list)),
                ("distance_m", models.FloatField(blank=True, null=True)),
                ("min_lat", models.FloatField(blank=True, null=True)),
                ("min_lon", models.FloatField(blank=True, null=True)),
                ("max_lat", models.FloatField(blank=True, null=True)),
                ("max_lon", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="drive_test.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("altitude", models.FloatField(blank=True, null=True)),
                ("speed", models.FloatField(blank=True, null=True)),
                ("heading", models.FloatField(blank=True, null=True)),
                ("hdop", models.FloatField(blank=True, null=True)),
                (
                    "technology",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GSM", "2G (GSM)"),
                            ("UMTS", "3G (UMTS)"),
                            ("LTE", "4G (LTE)"),
                            ("NR", "5G (NR)"),
                        ],
                        max_length=8,
                    ),
                ),
                ("mcc", models.CharField(blank=True, max_length=3)),
                ("mnc", models.CharField(blank=True, max_length=3)),
                ("plmn", models.CharField(blank=True, max_length=6)),
                ("obs_cell_id", models.CharField(blank=True, max_length=40)),
                ("obs_pci", models.IntegerField(blank=True, null=True)),
                ("obs_psc", models.IntegerField(blank=True, null=True)),
                ("obs_bsic", models.IntegerField(blank=True, null=True)),
                ("obs_arfcn", models.IntegerField(blank=True, null=True)),
                ("frequency", models.FloatField(blank=True, null=True)),
                ("band", models.CharField(blank=True, max_length=20)),
                ("channel", models.IntegerField(blank=True, null=True)),
                (
                    "match_method",
                    models.CharField(
                        choices=[
                            ("NONE", "Not matched"),
                            ("EXACT", "Exact identifier match"),
                            ("PCI_FREQ", "PCI + frequency match"),
                            ("NEAREST", "Nearest reference cell"),
                            ("MANUAL", "Manually assigned"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                ("match_confidence", models.FloatField(blank=True, null=True)),
                ("rsrp", models.FloatField(blank=True, null=True)),
                ("rsrq", models.FloatField(blank=True, null=True)),
                ("sinr", models.FloatField(blank=True, null=True)),
                ("rssi", models.FloatField(blank=True, null=True)),
                ("cqi", models.FloatField(blank=True, null=True)),
                ("ss_rsrp", models.FloatField(blank=True, null=True)),
                ("ss_rsrq", models.FloatField(blank=True, null=True)),
                ("ss_sinr", models.FloatField(blank=True, null=True)),
                ("rscp", models.FloatField(blank=True, null=True)),
                ("ecno", models.FloatField(blank=True, null=True)),
                ("rxlev", models.FloatField(blank=True, null=True)),
                ("rxqual", models.FloatField(blank=True, null=True)),
                (
                    "dl_throughput",
                    models.FloatField(blank=True, help_text="kbps", null=True),
                ),
                (
                    "ul_throughput",
                    models.FloatField(blank=True, help_text="kbps", null=True),
                ),
                ("latency_ms", models.FloatField(blank=True, null=True)),
                (
                    "packet_loss",
                    models.FloatField(blank=True, help_text="percent", null=True),
                ),
                ("event_type", models.CharField(blank=True, max_length=40)),
                ("event_status", models.CharField(blank=True, max_length=40)),
                ("is_valid", models.BooleanField(default=True)),
                ("quality_flags", models.JSONField(blank=True, default=list)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="drive_test.campaign",
                    ),
                ),
                (
                    "cell",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="serving_samples",
                        to="drive_test.cell",
                    ),
                ),
                (
                    "drive_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="drive_test.drivetestfile",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dt_samples",
                        to="reference.operator",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="samples",
                        to="drive_test.route",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ref",
                    models.CharField(
                        db_index=True, editable=False, max_length=40, unique=True
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("EXECUTIVE", "Executive Report"),
                            ("TECHNICAL", "Technical RF Report"),
                            ("COVERAGE", "Coverage Report"),
                            ("OPERATOR_COMPARISON", "Operator Comparison"),
                            ("ROUTE", "Route Report"),
                            ("CAMPAIGN", "Campaign Report"),
                            ("REGULATORY", "Regulatory Report"),
                        ],
                        max_length=24,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("params", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("GENERATING", "Generating"),
                            ("READY", "Ready"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("artifact_path", models.CharField(blank=True, max_length=1024)),
                ("artifact_format", models.CharField(blank=True, max_length=12)),
                ("error_message", models.TextField(blank=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="drive_test.campaign",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dt_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="drive_test.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="ProblemArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area_type",
                    models.CharField(help_text="e.g. Poor LTE Coverage", max_length=60),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, help_text="e.g. locality name", max_length=120
                    ),
                ),
                ("centroid_lat", models.FloatField(blank=True, null=True)),
                ("centroid_lon", models.FloatField(blank=True, null=True)),
                ("min_lat", models.FloatField(blank=True, null=True)),
                ("min_lon", models.FloatField(blank=True, null=True)),
                ("max_lat", models.FloatField(blank=True, null=True)),
                ("max_lon", models.FloatField(blank=True, null=True)),
                ("affected_distance_m", models.FloatField(blank=True, null=True)),
                ("sample_count", models.IntegerField(default=0)),
                (
                    "stats",
                    models.JSONField(
                        blank=True, default=dict, help_text="e.g. mean RSRP/SINR"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="MEDIUM",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_areas",
                        to="drive_test.campaign",
                    ),
                ),
                (
                    "dominant_cell",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dt_problem_areas",
                        to="drive_test.cell",
                    ),
                ),
            ],
            options={
                "ordering": ["-severity", "-sample_count"],
            },
        ),
        migrations.CreateModel(
            name="NeighborMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.IntegerField(default=0, help_text="0 = strongest")),
                (
                    "rat",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GSM", "2G (GSM)"),
                            ("UMTS", "3G (UMTS)"),
                            ("LTE", "4G (LTE)"),
                            ("NR", "5G (NR)"),
                        ],
                        max_length=8,
                    ),
                ),
                ("obs_pci", models.IntegerField(blank=True, null=True)),
                ("obs_psc", models.IntegerField(blank=True, null=True)),
                ("obs_bsic", models.IntegerField(blank=True, null=True)),
                ("obs_arfcn", models.IntegerField(blank=True, null=True)),
                ("rsrp", models.FloatField(blank=True, null=True)),
                ("rsrq", models.FloatField(blank=True, null=True)),
                ("rscp", models.FloatField(blank=True, null=True)),
                ("ecno", models.FloatField(blank=True, null=True)),
                ("rssi", models.FloatField(blank=True, null=True)),
                ("ss_rsrp", models.FloatField(blank=True, null=True)),
                (
                    "match_method",
                    models.CharField(
                        choices=[
                            ("NONE", "Not matched"),
                            ("EXACT", "Exact identifier match"),
                            ("PCI_FREQ", "PCI + frequency match"),
                            ("NEAREST", "Nearest reference cell"),
                            ("MANUAL", "Manually assigned"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                ("match_confidence", models.FloatField(blank=True, null=True)),
                (
                    "cell",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="neighbor_measurements",
                        to="drive_test.cell",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="neighbors",
                        to="drive_test.sample",
                    ),
                ),
            ],
            options={
                "ordering": ["sample", "rank"],
            },
        ),
        migrations.CreateModel(
            name="KpiThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        db_index=True,
                        help_text="e.g. rsrp, sinr, dl_throughput",
                        max_length=40,
                    ),
                ),
                (
                    "technology",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GSM", "2G (GSM)"),
                            ("UMTS", "3G (UMTS)"),
                            ("LTE", "4G (LTE)"),
                            ("NR", "5G (NR)"),
                        ],
                        max_length=8,
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=120)),
                ("bands", models.JSONField(default=list)),
                (
                    "unit",
                    models.CharField(
                        blank=True, help_text="e.g. dBm, dB, Mbps", max_length=20
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thresholds",
                        to="drive_test.campaign",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dt_thresholds",
                        to="reference.operator",
                    ),
                ),
            ],
            options={
                "ordering": ["metric", "technology"],
            },
        ),
        migrations.CreateModel(
            name="KpiResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("CAMPAIGN", "Campaign"),
                            ("CELL", "Cell"),
                            ("REGION", "Region"),
                            ("BIN", "Spatial bin"),
                            ("OPERATOR", "Operator"),
                            ("TECHNOLOGY", "Technology"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "scope_key",
                    models.CharField(
                        blank=True,
                        help_text="cell id / region / bin key",
                        max_length=120,
                    ),
                ),
                ("metric", models.CharField(max_length=40)),
                ("count", models.IntegerField(default=0)),
                ("min_value", models.FloatField(blank=True, null=True)),
                ("mean_value", models.FloatField(blank=True, null=True)),
                ("median_value", models.FloatField(blank=True, null=True)),
                ("p10_value", models.FloatField(blank=True, null=True)),
                ("p50_value", models.FloatField(blank=True, null=True)),
                ("p90_value", models.FloatField(blank=True, null=True)),
                ("max_value", models.FloatField(blank=True, null=True)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_results",
                        to="drive_test.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["scope_type", "scope_key", "metric"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=40)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        db_index=True,
                        default="MEDIUM",
                        max_length=8,
                    ),
                ),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "technology",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GSM", "2G (GSM)"),
                            ("UMTS", "3G (UMTS)"),
                            ("LTE", "4G (LTE)"),
                            ("NR", "5G (NR)"),
                        ],
                        max_length=8,
                    ),
                ),
                ("kpi", models.CharField(blank=True, max_length=40)),
                ("measured_value", models.FloatField(blank=True, null=True)),
                ("threshold_value", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("RESOLVED", "Resolved"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        default="OPEN",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="drive_test.campaign",
                    ),
                ),
                (
                    "cell",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dt_events",
                        to="drive_test.cell",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dt_events",
                        to="reference.operator",
                    ),
                ),
                (
                    "problem_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="drive_test.problemarea",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="drive_test.sample",
                    ),
                ),
            ],
            options={
                "ordering": ["-severity", "-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to="drive_test.project",
            ),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(
                fields=["campaign", "timestamp"], name="drive_test__campaig_a1639e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(
                fields=["latitude", "longitude"], name="drive_test__latitud_8af584_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(fields=["cell"], name="drive_test__cell_id_e88a0b_idx"),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(
                fields=["technology"], name="drive_test__technol_b8fe88_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="neighbormeasurement",
            constraint=models.UniqueConstraint(
                fields=("sample", "rank"), name="dt_neighbor_unique_rank"
            ),
        ),
        migrations.AddIndex(
            model_name="kpithreshold",
            index=models.Index(
                fields=["metric", "technology"], name="drive_test__metric_a228bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kpiresult",
            index=models.Index(
                fields=["campaign", "scope_type", "metric"],
                name="drive_test__campaig_8bdbb7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["campaign", "event_type"], name="drive_test__campaig_ad1dbb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="drivetestfile",
            index=models.Index(
                fields=["campaign", "status"], name="drive_test__campaig_d2051a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cell",
            index=models.Index(
                fields=["technology", "pci"], name="drive_test__technol_1ef115_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cell",
            index=models.Index(
                fields=["latitude", "longitude"], name="drive_test__latitud_b82e3b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cell",
            constraint=models.UniqueConstraint(
                fields=("operator", "technology", "cell_id"),
                name="dt_cell_unique_per_operator_tech",
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["project", "operator"], name="drive_test__project_e765d1_idx"
            ),
        ),
    ]
