# Generated by Django 4.2.30 on 2026-09-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drive_test", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="drivetestfile",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="drivetestfile",
            name="profile",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="drivetestfile",
            name="quality_report",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="drivetestfile",
            name="quality_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
