# Generated by Django 5.2.17 on 2026-09-28 09:56

import django.db.models.deletion
import drive_test.models.reports
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drive_test", "0002_seed_trp_parser_profile"),
        ("reference", "0011_alter_sourcepattern_decoder_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegulatoryReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_ref",
                    models.CharField(
                        default=drive_test.models.reports._generate_report_ref,
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("SESSION", "Session Report"),
                            ("COMPLIANCE", "Regulatory Compliance Report"),
                            ("OPERATOR", "Operator Report"),
                            ("PERIODIC", "Periodic Regulatory Report"),
                        ],
                        max_length=12,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("technology", models.CharField(blank=True, max_length=5)),
                ("date_from", models.DateField(blank=True, null=True)),
                ("date_to", models.DateField(blank=True, null=True)),
                ("session_count", models.IntegerField(default=0)),
                ("measurement_count", models.IntegerField(default=0)),
                ("finding_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("COMPLETED", "Completed"), ("FAILED", "Failed")],
                        default="COMPLETED",
                        max_length=10,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="drive_test/reports/%Y/%m/"
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="drive_test.district",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="reference.operator",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="drive_test.region",
                    ),
                ),
                (
                    "sessions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="regulatory_reports",
                        to="drive_test.drivetestsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
    ]
