# Generated by Django 5.2.17 on 2026-09-29 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drive_test", "0004_benchmark_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="radiomeasurement",
            name="c_over_i",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="radiomeasurement",
            name="rxqual",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="BeamMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ssb_index", models.SmallIntegerField()),
                ("is_serving", models.BooleanField(default=False)),
                ("ss_rsrp", models.FloatField(blank=True, null=True)),
                ("ss_rsrq", models.FloatField(blank=True, null=True)),
                ("ss_sinr", models.FloatField(blank=True, null=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "measurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beams",
                        to="drive_test.measurement",
                    ),
                ),
            ],
            options={
                "ordering": ["measurement", "ssb_index"],
                "indexes": [
                    models.Index(
                        fields=["measurement", "ssb_index"],
                        name="drive_test__measure_742ee6_idx",
                    )
                ],
                "unique_together": {("measurement", "ssb_index")},
            },
        ),
        migrations.CreateModel(
            name="CarrierMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cc_index", models.SmallIntegerField(help_text="0 = PCell")),
                ("is_primary", models.BooleanField(default=False)),
                ("arfcn", models.IntegerField(blank=True, null=True)),
                ("band", models.CharField(blank=True, max_length=20)),
                ("bandwidth_mhz", models.FloatField(blank=True, null=True)),
                ("rsrp", models.FloatField(blank=True, null=True)),
                ("rsrq", models.FloatField(blank=True, null=True)),
                ("sinr", models.FloatField(blank=True, null=True)),
                ("mimo_layers", models.SmallIntegerField(blank=True, null=True)),
                ("modulation", models.CharField(blank=True, max_length=20)),
                ("dl_throughput_kbps", models.FloatField(blank=True, null=True)),
                ("ul_throughput_kbps", models.FloatField(blank=True, null=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "measurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carriers",
                        to="drive_test.measurement",
                    ),
                ),
            ],
            options={
                "ordering": ["measurement", "cc_index"],
                "indexes": [
                    models.Index(
                        fields=["measurement", "cc_index"],
                        name="drive_test__measure_d1240f_idx",
                    )
                ],
                "unique_together": {("measurement", "cc_index")},
            },
        ),
        migrations.CreateModel(
            name="MeasurementEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occurred_at", models.DateTimeField(db_index=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("HO_ATTEMPT", "Handover attempt"),
                            ("HO_SUCCESS", "Handover success"),
                            ("HO_FAILURE", "Handover failure"),
                            ("PING_PONG", "Ping-pong handover"),
                            ("CELL_RESELECT", "Cell reselection"),
                            ("RAT_CHANGE", "Technology change"),
                            ("RLF", "Radio link failure"),
                            ("CALL_ATTEMPT", "Call attempt"),
                            ("CALL_SETUP", "Call setup"),
                            ("CALL_END", "Call end"),
                            ("CALL_DROP", "Call drop"),
                            ("CALL_BLOCK", "Call blocked"),
                            ("ATTACH", "Attach"),
                            ("DETACH", "Detach"),
                            ("BEARER_SETUP", "Bearer setup"),
                            ("BEARER_RELEASE", "Bearer release"),
                            ("RACH", "Random access"),
                            ("DATA_TEST", "Data test"),
                            ("PING", "Ping"),
                            ("DNS", "DNS resolution"),
                            ("HTTP", "HTTP transaction"),
                            ("IMS_REGISTER", "IMS registration"),
                            ("SIP", "SIP event"),
                            ("ANOMALY", "Measurement anomaly"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("technology", models.CharField(blank=True, max_length=5)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "measurement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="drive_test.measurement",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="drive_test.drivetestsession",
                    ),
                ),
                (
                    "source_cell",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_sources",
                        to="drive_test.cell",
                    ),
                ),
                (
                    "target_cell",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_targets",
                        to="drive_test.cell",
                    ),
                ),
            ],
            options={
                "ordering": ["session", "occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "occurred_at"],
                        name="drive_test__session_ada72d_idx",
                    ),
                    models.Index(
                        fields=["session", "event_type"],
                        name="drive_test__session_00272c_idx",
                    ),
                    models.Index(
                        fields=["event_type", "severity"],
                        name="drive_test__event_t_997d25_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NeighbourMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank",
                    models.SmallIntegerField(
                        help_text="0 = strongest detected neighbour"
                    ),
                ),
                ("rat", models.CharField(blank=True, max_length=5)),
                ("obs_pci", models.IntegerField(blank=True, null=True)),
                ("obs_psc", models.IntegerField(blank=True, null=True)),
                ("obs_bsic", models.IntegerField(blank=True, null=True)),
                ("obs_arfcn", models.IntegerField(blank=True, null=True)),
                ("rssi", models.FloatField(blank=True, null=True)),
                ("rscp", models.FloatField(blank=True, null=True)),
                ("ecio", models.FloatField(blank=True, null=True)),
                ("rsrp", models.FloatField(blank=True, null=True)),
                ("rsrq", models.FloatField(blank=True, null=True)),
                ("ss_rsrp", models.FloatField(blank=True, null=True)),
                ("match_confidence", models.FloatField(blank=True, null=True)),
                ("match_method", models.CharField(blank=True, max_length=30)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "cell",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="neighbour_measurements",
                        to="drive_test.cell",
                    ),
                ),
                (
                    "measurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="neighbours",
                        to="drive_test.measurement",
                    ),
                ),
            ],
            options={
                "ordering": ["measurement", "rank"],
                "indexes": [
                    models.Index(
                        fields=["measurement", "rank"],
                        name="drive_test__measure_5d8c03_idx",
                    ),
                    models.Index(
                        fields=["cell"], name="drive_test__cell_id_47425e_idx"
                    ),
                ],
                "unique_together": {("measurement", "rank")},
            },
        ),
    ]
