# Generated by Django 4.2.23 on 2026-05-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='imsrecord',
            new_name='ims_records_start_t_9cc8c5_idx',
            old_name='ims_records_start_t_idx',
        ),
        migrations.RenameIndex(
            model_name='imsrecord',
            new_name='ims_records_calling_33b740_idx',
            old_name='ims_records_calling_idx',
        ),
        migrations.RenameIndex(
            model_name='imsrecord',
            new_name='ims_records_called__f23411_idx',
            old_name='ims_records_called_idx',
        ),
        migrations.RenameIndex(
            model_name='imsrecord',
            new_name='ims_records_imsi_86026c_idx',
            old_name='ims_records_imsi_idx',
        ),
        migrations.RenameIndex(
            model_name='imsrecord',
            new_name='ims_records_session_998446_idx',
            old_name='ims_records_session_idx',
        ),
        migrations.RenameIndex(
            model_name='imsrecord',
            new_name='ims_records_file_id_01fbc8_idx',
            old_name='ims_records_file_rt_idx',
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='access_network_info',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='called_impi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='called_imsi',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='called_min',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='calling_impi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='calling_imsi',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='calling_min',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='imei',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='media_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='private_user_identity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='served_subscriber_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='imsrecord',
            index=models.Index(fields=['calling_imsi', 'start_time'], name='ims_records_calling_c76373_idx'),
        ),
        migrations.AddIndex(
            model_name='imsrecord',
            index=models.Index(fields=['called_imsi', 'start_time'], name='ims_records_called__b9aafd_idx'),
        ),
    ]
