# Generated by Django 4.2.23 on 2026-05-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_rename_ims_records_start_t_idx_ims_records_start_t_9cc8c5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imsrecord',
            name='apn',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='cell_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='enodeb_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='forwarded_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='lac',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='redirecting_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='serving_plmn',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='tac',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='technology',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='ue_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
