# Generated by Django 4.2.23 on 2026-05-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0003_imsrecord_apn_imsrecord_cell_id_imsrecord_enodeb_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imsrecord',
            name='accounting_record_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='additional_called_party',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='additional_calling_party',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='called_asserted_identity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='connected_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='ims_3gpp_online_charging',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='in_bypass',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='in_call_reference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='in_scf_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='in_service_key',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='incomplete_cdr_indication',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='is_volte_call_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='network_call_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='province',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='requested_party_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='retransmission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='roam_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='sdp_media_components',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='sdp_media_identifier',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='sip_from_uri',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='tads_indication',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='user_agent_value',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='visited_network_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
