# Generated by Django 4.2.23 on 2026-05-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0004_imsrecord_accounting_record_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imsrecord',
            name='default_call_handling',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
