# Generated by Django 4.2.23 on 2026-05-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0005_imsrecord_default_call_handling'),
    ]

    operations = [
        migrations.AddField(
            model_name='imsrecord',
            name='access_network_spec',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='call_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='called_asserted_identity_raw',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='codec',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='dialled_party_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='private_user_equipment_info_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='private_user_equipment_info_value',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='requested_party_address_raw',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='rtp_port',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='rtp_protocol',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='sip_codec_payload',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='subscriber_role',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='imsrecord',
            name='telephone_event_payload',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
