# Generated by Django 4.2.23 on 2026-05-16 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0006_imsrecord_access_network_spec_imsrecord_call_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imsrecord',
            name='paired_record',
            field=models.ForeignKey(blank=True, help_text='Linked CDR pair (originating ↔ terminating record with the same ICID).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paired_records_reverse', to='ims.imsrecord'),
        ),
    ]
