# Generated by Django 4.2.23 on 2026-04-23 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('rule_type', models.CharField(choices=[('VALIDATION', 'Validation'), ('TRANSFORMATION', 'Transformation'), ('ENRICHMENT', 'Enrichment'), ('FILTERING', 'Filtering'), ('RATING', 'Rating'), ('AGGREGATION', 'Aggregation')], default='VALIDATION', max_length=20)),
                ('stream', models.CharField(choices=[('ALL', 'All Streams'), ('MSC', 'MSC (Voice/SMS)'), ('PGW', 'PGW (4G Data)'), ('SGSN', 'SGSN (2G/3G)'), ('SGW', 'SGW (4G S-GW)')], default='ALL', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DRAFT', 'Draft'), ('TESTING', 'Testing')], default='DRAFT', max_length=10)),
                ('priority', models.IntegerField(choices=[(10, 'Low'), (50, 'Normal'), (80, 'High'), (100, 'Critical')], default=50)),
                ('description', models.TextField(blank=True, help_text='Purpose and behavior of this rule')),
                ('condition', models.TextField(blank=True, help_text='JSON or expression defining when the rule triggers')),
                ('action', models.TextField(blank=True, help_text='JSON or expression defining what the rule does')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'businesslogic_rule',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RuleExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('APPLIED', 'Applied'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], max_length=10)),
                ('records_in', models.IntegerField(default=0, help_text='Records evaluated')),
                ('records_out', models.IntegerField(default=0, help_text='Records affected / passed')),
                ('message', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='businesslogic.businessrule')),
            ],
            options={
                'db_table': 'businesslogic_execution',
                'ordering': ['-executed_at'],
            },
        ),
    ]
