# Generated by Django 4.2.23 on 2026-04-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesslogic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessrule',
            name='rule_type',
            field=models.CharField(choices=[('VALIDATION', 'Validation'), ('TRANSFORMATION', 'Transformation'), ('ENRICHMENT', 'Enrichment'), ('FILTERING', 'Filtering'), ('RATING', 'Rating'), ('AGGREGATION', 'Aggregation'), ('CORRELATION', 'Correlation'), ('DETECTION', 'Detection'), ('ERROR_HANDLING', 'Error Handling')], default='VALIDATION', max_length=20),
        ),
    ]
