# Generated by Django 4.2.23 on 2026-04-22 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SGWRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(db_index=True, max_length=50)),
                ('service_type', models.CharField(default='DATA', max_length=20)),
                ('charging_id', models.CharField(blank=True, max_length=50, null=True)),
                ('calling_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('called_number', models.CharField(blank=True, max_length=100)),
                ('imsi', models.CharField(blank=True, db_index=True, max_length=20)),
                ('imei', models.CharField(blank=True, max_length=20)),
                ('start_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('data_volume_up', models.CharField(default='0', max_length=50)),
                ('data_volume_down', models.CharField(default='0', max_length=50)),
                ('apn', models.CharField(blank=True, db_index=True, max_length=100)),
                ('pdn_type', models.CharField(blank=True, max_length=20)),
                ('rat_type', models.CharField(blank=True, max_length=20)),
                ('sgw_address', models.CharField(blank=True, max_length=50)),
                ('pgw_address', models.CharField(blank=True, max_length=50)),
                ('node_id', models.CharField(blank=True, max_length=100)),
                ('cell_id', models.CharField(blank=True, max_length=50)),
                ('lac', models.CharField(blank=True, max_length=20)),
                ('serving_plmn', models.CharField(blank=True, max_length=10)),
                ('cause_for_closing', models.CharField(blank=True, max_length=50)),
                ('is_roaming', models.BooleanField(default=False)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('INVALID', 'Invalid'), ('DUPLICATE', 'Duplicate')], default='VALID', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sgw_records', to='collection.cdrfile')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.datasource')),
            ],
            options={
                'verbose_name': 'SGW CDR Record',
                'verbose_name_plural': 'SGW CDR Records',
                'db_table': 'sgw_records',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['start_time', 'apn'], name='sgw_records_start_t_b3f972_idx'), models.Index(fields=['calling_number', 'start_time'], name='sgw_records_calling_de7a2b_idx'), models.Index(fields=['imsi', 'start_time'], name='sgw_records_imsi_1c4b25_idx'), models.Index(fields=['file', 'record_type'], name='sgw_records_file_id_8129e6_idx'), models.Index(fields=['apn', 'start_time'], name='sgw_records_apn_c8c17d_idx')],
            },
        ),
    ]
