# Generated by Django 4.2.23 on 2026-04-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgw', '0004_add_prepaid_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='sgwrecord',
            name='eci',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sgwrecord',
            name='tac',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
