# Generated by Django 4.2.23 on 2026-05-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgw', '0005_sgwrecord_eci_sgwrecord_tac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sgwrecord',
            name='data_volume_down',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sgwrecord',
            name='data_volume_up',
            field=models.BigIntegerField(default=0),
        ),
    ]
